Leptonica: prog/alphaxform_reg.c File Reference
alphaxform_reg.c File Reference
Tests the alpha blending functions when used with various transforms (scaling, rotation, affine, projective, bilinear)
#include "allheaders.h"
Functions
static void MakePtas (l_int32 i, l_int32 npts, PTA **pptas, PTA **pptad)
main (int argc, char **argv)
Variables
static const l_int32 x1 [] = { 300, 300, 300, 95, 32 }
static const l_int32 y1 [] = { 1200, 1200, 1250, 2821, 934 }
static const l_int32 x2 [] = { 1200, 1200, 1125, 1432, 487 }
static const l_int32 y2 [] = { 1100, 1100, 1100, 2682, 934 }
static const l_int32 x3 [] = { 200, 200, 200, 232, 32 }
static const l_int32 y3 [] = { 200, 200, 200, 657, 67 }
static const l_int32 x4 [] = { 1200, 1200, 1125, 1432, 487 }
static const l_int32 y4 [] = { 200, 200, 200, 242, 84 }
static const l_int32 xp1 [] = { 500, 300, 350, 117, 32 }
static const l_int32 yp1 [] = { 1700, 1400, 1100, 2629, 934 }
static const l_int32 xp2 [] = { 850, 400, 1100, 1664, 487 }
static const l_int32 yp2 [] = { 850, 500, 1300, 2432, 804 }
static const l_int32 xp3 [] = { 450, 200, 400, 183, 61 }
static const l_int32 yp3 [] = { 300, 300, 400, 490, 83 }
static const l_int32 xp4 [] = { 850, 1000, 1100, 1664, 487 }
static const l_int32 yp4 [] = { 350, 350, 400, 532, 114 }
Detailed Description
Tests the alpha blending functions when used with various transforms (scaling, rotation, affine, projective, bilinear)
Definition in file alphaxform_reg.c.
Function Documentation
static void MakePtas (l_int32 i, l_int32 npts, PTA ** pptas, PTA ** pptad) [static]
Definition at line 315 of file alphaxform_reg.c.
References ptaAddPt(), ptaCreate(), x1, x2, x3, x4, xp1, xp2, xp3, xp4, y1, y2, y3, y4, yp1, yp2, yp3, and yp4.
Referenced by main().
main (int argc, char ** argv)
Definition at line 54 of file alphaxform_reg.c.
References L_RegParams::display, IFF_PNG, MakePtas(), NULL, pixAffinePtaGammaXform(), pixAffinePtaWithAlpha(), pixBilinearPtaGammaXform(), pixBilinearPtaWithAlpha(), pixBlendWithGrayMask(), pixCreate(), pixDestroy(), pixDisplayWithTitle(), pixProjectivePtaGammaXform(), pixProjectivePtaWithAlpha(), pixRead(), pixRotateGammaXform(), pixRotateWithAlpha(), pixScale(), pixScaleGammaXform(), pixScaleWithAlpha(), pixSetAll(), ptaDestroy(), regTestCleanup(), regTestSetup(), and regTestWritePixAndCheck().
Variable Documentation
const l_int32 x1[] = { 300, 300, 300, 95, 32 } [static]
Definition at line 33 of file alphaxform_reg.c.
Referenced by MakePtas().
const l_int32 y1[] = { 1200, 1200, 1250, 2821, 934 } [static]
Definition at line 34 of file alphaxform_reg.c.
Referenced by MakePtas().
const l_int32 x2[] = { 1200, 1200, 1125, 1432, 487 } [static]
Definition at line 35 of file alphaxform_reg.c.
Referenced by MakePtas().
const l_int32 y2[] = { 1100, 1100, 1100, 2682, 934 } [static]
Definition at line 36 of file alphaxform_reg.c.
Referenced by MakePtas().
const l_int32 x3[] = { 200, 200, 200, 232, 32 } [static]
Definition at line 37 of file alphaxform_reg.c.
Referenced by MakePtas().
const l_int32 y3[] = { 200, 200, 200, 657, 67 } [static]
Definition at line 38 of file alphaxform_reg.c.
Referenced by MakePtas().
const l_int32 x4[] = { 1200, 1200, 1125, 1432, 487 } [static]
Definition at line 39 of file alphaxform_reg.c.
Referenced by getBilinearXformCoeffs(), getProjectiveXformCoeffs(), MakePtas(), and ptaConvertToBoxa().
const l_int32 y4[] = { 200, 200, 200, 242, 84 } [static]
Definition at line 40 of file alphaxform_reg.c.
Referenced by getBilinearXformCoeffs(), getProjectiveXformCoeffs(), MakePtas(), and ptaConvertToBoxa().
const l_int32 xp1[] = { 500, 300, 350, 117, 32 } [static]
Definition at line 43 of file alphaxform_reg.c.
Referenced by MakePtas().
const l_int32 yp1[] = { 1700, 1400, 1100, 2629, 934 } [static]
Definition at line 44 of file alphaxform_reg.c.
Referenced by MakePtas().
const l_int32 xp2[] = { 850, 400, 1100, 1664, 487 } [static]
Definition at line 45 of file alphaxform_reg.c.
Referenced by MakePtas().
const l_int32 yp2[] = { 850, 500, 1300, 2432, 804 } [static]
Definition at line 46 of file alphaxform_reg.c.
Referenced by MakePtas().
const l_int32 xp3[] = { 450, 200, 400, 183, 61 } [static]
Definition at line 47 of file alphaxform_reg.c.
Referenced by MakePtas().
const l_int32 yp3[] = { 300, 300, 400, 490, 83 } [static]
Definition at line 48 of file alphaxform_reg.c.
Referenced by MakePtas().
const l_int32 xp4[] = { 850, 1000, 1100, 1664, 487 } [static]
Definition at line 49 of file alphaxform_reg.c.
Referenced by MakePtas().
const l_int32 yp4[] = { 350, 350, 400, 532, 114 } [static]
Definition at line 50 of file alphaxform_reg.c.
Referenced by MakePtas().