Leptonica: src/bbuffer.c File Reference
bbuffer.c File Reference
Implements ByteBuffer, a byte queue; used for zlib comp/decomp in memory.
#include <string.h>
#include "allheaders.h"
Functions
BBUFFER * bbufferCreate (l_uint8 *indata, l_int32 nalloc)
void bbufferDestroy (BBUFFER **pbb)
l_uint8 * bbufferDestroyAndSaveData (BBUFFER **pbb, size_t *pnbytes)
l_int32 bbufferRead (BBUFFER *bb, l_uint8 *src, l_int32 nbytes)
l_int32 bbufferReadStream (BBUFFER *bb, FILE *fp, l_int32 nbytes)
l_int32 bbufferExtendArray (BBUFFER *bb, l_int32 nbytes)
l_int32 bbufferWrite (BBUFFER *bb, l_uint8 *dest, size_t nbytes, size_t *pnout)
l_int32 bbufferWriteStream (BBUFFER *bb, FILE *fp, size_t nbytes, size_t *pnout)
l_int32 bbufferBytesToWrite (BBUFFER *bb, size_t *pnbytes)
Variables
static const l_int32 INITIAL_BUFFER_ARRAYSIZE = 1024
Detailed Description
Implements ByteBuffer, a byte queue; used for zlib comp/decomp in memory.
Definition in file bbuffer.c.
Function Documentation
BBUFFER* bbufferCreate (l_uint8 * indata, l_int32 nalloc)
bbufferCreate()
Input: buffer address in memory (<optional>) size of byte array to be alloc'd (0 for default) Return: bbuffer, or null on error
Notes: (1) If a buffer address is given, you should read all the data in. (2) Allocates a bbuffer with associated byte array of the given size. If a buffer address is given, it then reads the number of bytes into the byte array.
Definition at line 108 of file bbuffer.c.
References ByteBuffer::array, CALLOC, ERROR_PTR, INITIAL_BUFFER_ARRAYSIZE, ByteBuffer::n, L_Bytea::nalloc, ByteBuffer::nalloc, NULL, ByteBuffer::nwritten, and PROCNAME.
Referenced by ccbaWriteStream(), main(), zlibCompress(), and zlibUncompress().
void bbufferDestroy (BBUFFER ** pbb)
bbufferDestroy()
Input: &bbuffer (<to be="" nulled>="">) Return: void
Notes: (1) Destroys the byte array in the bbuffer and then the bbuffer; then nulls the contents of the input ptr.
Definition at line 147 of file bbuffer.c.
References ByteBuffer::array, FREE, L_WARNING, NULL, and PROCNAME.
Referenced by bbufferDestroyAndSaveData(), main(), zlibCompress(), and zlibUncompress().
l_uint8* bbufferDestroyAndSaveData (BBUFFER ** pbb, size_t * pnbytes)
bbufferDestroyAndSaveData()
Input: &bbuffer (<to be="" nulled>="">) &nbytes (<return> number of bytes saved in array) Return: barray (newly allocated array of data)
Notes: (1) Copies data to newly allocated array; then destroys the bbuffer.
Definition at line 181 of file bbuffer.c.
References ByteBuffer::array, bbufferDestroy(), CALLOC, L_WARNING, ByteBuffer::n, NULL, ByteBuffer::nwritten, and PROCNAME.
Referenced by ccbaWriteStream(), zlibCompress(), and zlibUncompress().
l_int32 bbufferRead (BBUFFER * bb, l_uint8 * src, l_int32 nbytes)
bbufferRead()
Input: bbuffer src (source memory buffer from which bytes are read) nbytes (bytes to be read) Return: 0 if OK, 1 on error
Notes: (1) For a read after write, first remove the written bytes by shifting the unwritten bytes in the array, then check if there is enough room to add the new bytes. If not, realloc with bbufferExpandArray(), resulting in a second writing of the unwritten bytes. While less efficient, this is simpler than making a special case of reallocNew().
Definition at line 239 of file bbuffer.c.
References ByteBuffer::array, bbufferExtendArray(), ERROR_INT, L_MAX, ByteBuffer::n, ByteBuffer::nalloc, ByteBuffer::nwritten, and PROCNAME.
Referenced by ccbaWriteStream(), main(), zlibCompress(), and zlibUncompress().
l_int32 bbufferReadStream (BBUFFER * bb, FILE * fp, l_int32 nbytes)
bbufferReadStream()
Input: bbuffer fp (source stream from which bytes are read) nbytes (bytes to be read) Return: 0 if OK, 1 on error
Definition at line 286 of file bbuffer.c.
References ByteBuffer::array, bbufferExtendArray(), ERROR_INT, L_MAX, ByteBuffer::n, ByteBuffer::nalloc, ByteBuffer::nwritten, and PROCNAME.
l_int32 bbufferExtendArray (BBUFFER * bb, l_int32 nbytes)
bbufferExtendArray()
Input: bbuffer nbytes (number of bytes to extend array size) Return: 0 if OK, 1 on error
Notes: (1) reallocNew() copies all bb->nalloc bytes, even though only bb->n are data.
Definition at line 336 of file bbuffer.c.
References ByteBuffer::array, ERROR_INT, ByteBuffer::nalloc, NULL, PROCNAME, and reallocNew().
Referenced by bbufferRead(), and bbufferReadStream().
l_int32 bbufferWrite (BBUFFER * bb, l_uint8 * dest, size_t nbytes, size_t * pnout)
bbufferWrite()
Input: bbuffer dest (dest memory buffer to which bytes are written) nbytes (bytes requested to be written) &nout (<return> bytes actually written) Return: 0 if OK, 1 on error
Definition at line 368 of file bbuffer.c.
References ByteBuffer::array, ERROR_INT, L_MIN, ByteBuffer::n, ByteBuffer::nwritten, and PROCNAME.
Referenced by main(), zlibCompress(), and zlibUncompress().
l_int32 bbufferWriteStream (BBUFFER * bb, FILE * fp, size_t nbytes, size_t * pnout)
bbufferWriteStream()
Input: bbuffer fp (dest stream to which bytes are written) nbytes (bytes requested to be written) &nout (<return> bytes actually written) Return: 0 if OK, 1 on error
Definition at line 420 of file bbuffer.c.
References ByteBuffer::array, ERROR_INT, L_MIN, ByteBuffer::n, ByteBuffer::nwritten, and PROCNAME.
Referenced by main().
l_int32 bbufferBytesToWrite (BBUFFER * bb, size_t * pnbytes)
bbufferBytesToWrite()
Input: bbuffer &nbytes (<return>) Return: 0 if OK; 1 on error
Definition at line 474 of file bbuffer.c.
References ERROR_INT, ByteBuffer::n, ByteBuffer::nwritten, and PROCNAME.
Variable Documentation
const l_int32 INITIAL_BUFFER_ARRAYSIZE = 1024 [static]
Definition at line 88 of file bbuffer.c.
Referenced by bbufferCreate().