Leptonica: prog/bilinear_reg.c File Reference
bilinear_reg.c File Reference
Tests various bilinear transformations: pixBilinearSampledPta() and pixBilinearPta().
#include <stdio.h>
#include <stdlib.h>
#include "allheaders.h"
Defines
#define ALL 1
#define ADDED_BORDER_PIXELS 500
Functions
static void MakePtas (l_int32 i, PTA **pptas, PTA **pptad)
main (int argc, char **argv)
Variables
static const l_int32 x1 [] = { 32, 32, 32}
static const l_int32 y1 [] = { 150, 150, 150}
static const l_int32 x2 [] = { 520, 520, 520}
static const l_int32 y2 [] = { 150, 150, 150}
static const l_int32 x3 [] = { 32, 32, 32}
static const l_int32 y3 [] = { 612, 612, 612}
static const l_int32 x4 [] = { 520, 520, 520}
static const l_int32 y4 [] = { 612, 612, 612}
static const l_int32 xp1 [] = { 32, 32, 32}
static const l_int32 yp1 [] = { 150, 150, 150}
static const l_int32 xp2 [] = { 520, 520, 520}
static const l_int32 yp2 [] = { 44, 124, 140}
static const l_int32 xp3 [] = { 32, 32, 32}
static const l_int32 yp3 [] = { 612, 612, 612}
static const l_int32 xp4 [] = { 520, 520, 520}
static const l_int32 yp4 [] = { 694, 624, 622}
Detailed Description
Tests various bilinear transformations: pixBilinearSampledPta() and pixBilinearPta().
Definition in file bilinear_reg.c.
Define Documentation
#define ALL 1
Definition at line 48 of file bilinear_reg.c.
#define ADDED_BORDER_PIXELS 500
Definition at line 49 of file bilinear_reg.c.
Referenced by main().
Function Documentation
static void MakePtas (l_int32 i, PTA ** pptas, PTA ** pptad) [static]
Definition at line 169 of file bilinear_reg.c.
References ptaAddPt(), ptaCreate(), x1, x2, x3, x4, xp1, xp2, xp3, xp4, y1, y2, y3, y4, yp1, yp2, yp3, and yp4.
Referenced by main().
main (int argc, char ** argv)
Definition at line 52 of file bilinear_reg.c.
References ADDED_BORDER_PIXELS, ERROR_INT, IFF_PNG, L_BRING_IN_WHITE, MakePtas(), pixaCreate(), pixAddBorder(), pixaDestroy(), pixaDisplay(), pixBilinearPta(), pixBilinearSampledPta(), pixDestroy(), pixDisplay(), pixInvert(), pixRead(), pixRemoveBorder(), pixSaveTiled(), pixScaleToGray3(), pixWrite(), pixXor(), ptaDestroy(), startTimer(), and stopTimer().
Variable Documentation
const l_int32 x1[] = { 32, 32, 32} [static]
Definition at line 30 of file bilinear_reg.c.
Referenced by MakePtas().
const l_int32 y1[] = { 150, 150, 150} [static]
Definition at line 31 of file bilinear_reg.c.
Referenced by MakePtas().
const l_int32 x2[] = { 520, 520, 520} [static]
Definition at line 32 of file bilinear_reg.c.
Referenced by MakePtas().
const l_int32 y2[] = { 150, 150, 150} [static]
Definition at line 33 of file bilinear_reg.c.
Referenced by MakePtas().
const l_int32 x3[] = { 32, 32, 32} [static]
Definition at line 34 of file bilinear_reg.c.
Referenced by MakePtas().
const l_int32 y3[] = { 612, 612, 612} [static]
Definition at line 35 of file bilinear_reg.c.
Referenced by MakePtas().
const l_int32 x4[] = { 520, 520, 520} [static]
Definition at line 36 of file bilinear_reg.c.
Referenced by MakePtas().
const l_int32 y4[] = { 612, 612, 612} [static]
Definition at line 37 of file bilinear_reg.c.
Referenced by MakePtas().
const l_int32 xp1[] = { 32, 32, 32} [static]
Definition at line 39 of file bilinear_reg.c.
Referenced by MakePtas().
const l_int32 yp1[] = { 150, 150, 150} [static]
Definition at line 40 of file bilinear_reg.c.
Referenced by MakePtas().
const l_int32 xp2[] = { 520, 520, 520} [static]
Definition at line 41 of file bilinear_reg.c.
Referenced by MakePtas().
const l_int32 yp2[] = { 44, 124, 140} [static]
Definition at line 42 of file bilinear_reg.c.
Referenced by MakePtas().
const l_int32 xp3[] = { 32, 32, 32} [static]
Definition at line 43 of file bilinear_reg.c.
Referenced by MakePtas().
const l_int32 yp3[] = { 612, 612, 612} [static]
Definition at line 44 of file bilinear_reg.c.
Referenced by MakePtas().
const l_int32 xp4[] = { 520, 520, 520} [static]
Definition at line 45 of file bilinear_reg.c.
Referenced by MakePtas().
const l_int32 yp4[] = { 694, 624, 622} [static]
Definition at line 46 of file bilinear_reg.c.
Referenced by MakePtas().