Leptonica: prog/binarize_reg.c File Reference
binarize_reg.c File Reference
Tests Sauvola local binarization using pixSauvolaBinarize() and pixSauvolaBinarizeTiled().
#include "allheaders.h"
Functions
PIX * PixTest1 (PIX *pixs, l_int32 size, l_float32 factor, L_REGPARAMS *rp)
PIX * PixTest2 (PIX *pixs, l_int32 size, l_float32 factor, l_int32 nx, l_int32 ny, L_REGPARAMS *rp)
void PixTest3 (PIX *pixs, l_int32 size, l_float32 factor, l_int32 nx, l_int32 ny, l_int32 paircount, L_REGPARAMS *rp)
main (int argc, char **argv)
Detailed Description
Tests Sauvola local binarization using pixSauvolaBinarize() and pixSauvolaBinarizeTiled().
Definition in file binarize_reg.c.
Function Documentation
PIX * PixTest1 (PIX * pixs, l_int32 size, l_float32 factor, L_REGPARAMS * rp)
Definition at line 70 of file binarize_reg.c.
References L_RegParams::display, IFF_JFIF_JPEG, IFF_PNG, L_RegParams::index, NULL, pixaCreate(), pixaDestroy(), pixaDisplay(), pixDestroy(), pixDisplayWithTitle(), pixGetDimensions(), pixSauvolaBinarize(), pixSaveTiled(), regTestWritePixAndCheck(), startTimer(), and stopTimer().
Referenced by main(), and PixTest3().
PIX * PixTest2 (PIX * pixs, l_int32 size, l_float32 factor, l_int32 nx, l_int32 ny, L_REGPARAMS * rp)
Definition at line 112 of file binarize_reg.c.
References L_RegParams::display, IFF_JFIF_JPEG, IFF_PNG, L_RegParams::index, NULL, pixaCreate(), pixaDestroy(), pixaDisplay(), pixDestroy(), pixDisplayWithTitle(), pixGetDimensions(), pixSauvolaBinarizeTiled(), pixSaveTiled(), regTestWritePixAndCheck(), startTimer(), and stopTimer().
Referenced by main(), and PixTest3().
void PixTest3 (PIX * pixs, l_int32 size, l_float32 factor, l_int32 nx, l_int32 ny, l_int32 paircount, L_REGPARAMS * rp)
Definition at line 153 of file binarize_reg.c.
References pixDestroy(), PixTest1(), PixTest2(), and regTestComparePix().
Referenced by main().
main (int argc, char ** argv)
Definition at line 30 of file binarize_reg.c.
References L_RegParams::display, IFF_PNG, NULL, pixContrastNorm(), pixDestroy(), pixDisplayWithTitle(), pixRead(), pixSauvolaBinarizeTiled(), PixTest1(), PixTest2(), PixTest3(), regTestCleanup(), regTestComparePix(), regTestSetup(), and regTestWritePixAndCheck().