Leptonica: src/binexpandlow.c File Reference
binexpandlow.c File Reference
Low-level implementation of integer upscaling.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "allheaders.h"
Functions
l_int32 expandBinaryPower2Low (l_uint32 *datad, l_int32 wd, l_int32 hd, l_int32 wpld, l_uint32 *datas, l_int32 ws, l_int32 hs, l_int32 wpls, l_int32 factor)
l_uint16 * makeExpandTab2x (void)
l_uint32 * makeExpandTab4x (void)
l_uint32 * makeExpandTab8x (void)
Variables
static l_uint32 expandtab16 []
Detailed Description
Low-level implementation of integer upscaling.
Definition in file binexpandlow.c.
Function Documentation
l_int32 expandBinaryPower2Low (l_uint32 * datad, l_int32 wd, l_int32 hd, l_int32 wpld, l_uint32 * datas, l_int32 ws, l_int32 hs, l_int32 wpls, l_int32 factor)
expandBinaryPower2Low()
Definition at line 46 of file binexpandlow.c.
References ERROR_INT, expandtab16, FREE, GET_DATA_BYTE, GET_DATA_DIBIT, GET_DATA_QBIT, L_WARNING_INT, makeExpandTab2x(), makeExpandTab4x(), makeExpandTab8x(), NULL, PROCNAME, and SET_DATA_TWO_BYTES.
Referenced by pixExpandBinaryPower2().
l_uint16* makeExpandTab2x (void)
Definition at line 141 of file binexpandlow.c.
References CALLOC, ERROR_PTR, NULL, and PROCNAME.
Referenced by expandBinaryPower2Low().
l_uint32* makeExpandTab4x (void)
Definition at line 175 of file binexpandlow.c.
References CALLOC, ERROR_PTR, NULL, and PROCNAME.
Referenced by expandBinaryPower2Low().
l_uint32* makeExpandTab8x (void)
Definition at line 209 of file binexpandlow.c.
References CALLOC, ERROR_PTR, NULL, and PROCNAME.
Referenced by expandBinaryPower2Low().
Variable Documentation
l_uint32 expandtab16[] [static]
Initial value:
 {
            0x00000000, 0x0000ffff, 0xffff0000, 0xffffffff}
Definition at line 35 of file binexpandlow.c.
Referenced by expandBinaryPower2Low().