Leptonica: prog/binmorph1_reg.c File Reference
binmorph1_reg.c File Reference
This is a thorough regression test of different methods for doing binary morphology.
#include "allheaders.h"
Defines
#define WIDTH 21
#define HEIGHT 15
#define TEST_SYMMETRIC 0
Functions
main (int argc, char **argv)
Detailed Description
This is a thorough regression test of different methods for doing binary morphology.
Definition in file binmorph1_reg.c.
Define Documentation
#define WIDTH 21
Definition at line 54 of file binmorph1_reg.c.
Referenced by main().
#define HEIGHT 15
Definition at line 55 of file binmorph1_reg.c.
Referenced by main().
#define TEST_SYMMETRIC 0
Definition at line 56 of file binmorph1_reg.c.
Function Documentation
main (int argc, char ** argv)
Definition at line 60 of file binmorph1_reg.c.
References ERROR_INT, FALSE, HEIGHT, IFF_PNG, NULL, pixAddBorder(), pixClose(), pixCloseBrick(), pixCloseBrickDwa(), pixCloseCompBrickDwa(), pixCloseSafe(), pixCloseSafeBrick(), pixCopy(), pixCreateTemplate(), pixDestroy(), pixDilate(), pixDilateBrick(), pixDilateBrickDwa(), pixDilateCompBrickDwa(), pixEqual(), pixErode(), pixErodeBrick(), pixErodeBrickDwa(), pixErodeCompBrickDwa(), pixMorphCompSequence(), pixMorphSequence(), pixMorphSequenceDwa(), pixOpen(), pixOpenBrick(), pixOpenBrickDwa(), pixOpenCompBrickDwa(), pixRead(), pixTransferAllData(), pixWrite(), pixXor(), resetMorphBoundaryCondition(), SEL_HIT, selCreateBrick(), selDestroy(), SYMMETRIC_MORPH_BC, TRUE, and WIDTH.