Leptonica: prog/binmorph4_reg.c File Reference
binmorph4_reg.c File Reference
Regression test for dwa brick morph operations.
#include <stdio.h>
#include <stdlib.h>
#include "allheaders.h"
Defines
#define TIMING 0
#define TEST_SYMMETRIC 0
Functions
l_int32 DoComparisonDwa1 (PIX *pixs, PIX *pixt1, PIX *pixt2, PIX *pixt3, PIX *pixt4, PIX *pixt5, PIX *pixt6, l_int32 isize)
l_int32 DoComparisonDwa2 (PIX *pixs, PIX *pixt1, PIX *pixt2, PIX *pixt3, PIX *pixt4, PIX *pixt5, PIX *pixt6, l_int32 isize)
l_int32 DoComparisonDwa3 (PIX *pixs, PIX *pixt1, PIX *pixt2, PIX *pixt3, PIX *pixt4, PIX *pixt5, PIX *pixt6, l_int32 isize)
l_int32 DoComparisonDwa4 (PIX *pixs, PIX *pixt1, PIX *pixt2, PIX *pixt3, PIX *pixt4, PIX *pixt5, PIX *pixt6, l_int32 isize)
l_int32 DoComparisonDwa5 (PIX *pixs, PIX *pixt1, PIX *pixt2, PIX *pixt3, PIX *pixt4, PIX *pixt5, PIX *pixt6, l_int32 isize)
l_int32 PixCompareDwa (l_int32 size, const char *type, PIX *pixt1, PIX *pixt2, PIX *pixt3, PIX *pixt4, PIX *pixt5, PIX *pixt6)
main (int argc, char **argv)
Detailed Description
Regression test for dwa brick morph operations.
Definition in file binmorph4_reg.c.
Define Documentation
#define TIMING 0
Definition at line 46 of file binmorph4_reg.c.
Referenced by DoComparisonDwa1(), DoComparisonDwa2(), DoComparisonDwa3(), DoComparisonDwa4(), and DoComparisonDwa5().
#define TEST_SYMMETRIC 0
Definition at line 56 of file binmorph4_reg.c.
Function Documentation
l_int32 DoComparisonDwa1 (PIX * pixs, PIX * pixt1, PIX * pixt2, PIX * pixt3, PIX * pixt4, PIX * pixt5, PIX * pixt6, l_int32 isize)
Definition at line 123 of file binmorph4_reg.c.
References IFF_PNG, pixCloseSafeBrick(), pixCloseSafeCompBrick(), PixCompareDwa(), pixDilateBrick(), pixDilateCompBrick(), pixDisplay(), pixErodeBrick(), pixErodeCompBrick(), pixOpenBrick(), pixOpenCompBrick(), pixWrite(), pixXor(), selectComposableSizes(), size, startTimer(), stopTimer(), and TIMING.
Referenced by main().
l_int32 DoComparisonDwa2 (PIX * pixs, PIX * pixt1, PIX * pixt2, PIX * pixt3, PIX * pixt4, PIX * pixt5, PIX * pixt6, l_int32 isize)
Definition at line 214 of file binmorph4_reg.c.
References pixCloseBrickDwa(), pixCloseSafeCompBrick(), PixCompareDwa(), pixDilateBrickDwa(), pixDilateCompBrick(), pixErodeBrickDwa(), pixErodeCompBrick(), pixOpenBrickDwa(), pixOpenCompBrick(), selectComposableSizes(), size, startTimer(), stopTimer(), and TIMING.
Referenced by main().
l_int32 DoComparisonDwa3 (PIX * pixs, PIX * pixt1, PIX * pixt2, PIX * pixt3, PIX * pixt4, PIX * pixt5, PIX * pixt6, l_int32 isize)
Definition at line 292 of file binmorph4_reg.c.
References IFF_PNG, pixCloseBrickDwa(), pixCloseCompBrickDwa(), PixCompareDwa(), pixDilateBrickDwa(), pixDilateCompBrickDwa(), pixErodeBrickDwa(), pixErodeCompBrickDwa(), pixOpenBrickDwa(), pixOpenCompBrickDwa(), pixWrite(), pixXor(), selectComposableSizes(), size, startTimer(), stopTimer(), and TIMING.
Referenced by main().
l_int32 DoComparisonDwa4 (PIX * pixs, PIX * pixt1, PIX * pixt2, PIX * pixt3, PIX * pixt4, PIX * pixt5, PIX * pixt6, l_int32 isize)
Definition at line 372 of file binmorph4_reg.c.
References pixCloseCompBrickDwa(), pixCloseSafeCompBrick(), PixCompareDwa(), pixDilateCompBrick(), pixDilateCompBrickDwa(), pixErodeCompBrick(), pixErodeCompBrickDwa(), pixOpenCompBrick(), pixOpenCompBrickDwa(), selectComposableSizes(), size, startTimer(), stopTimer(), and TIMING.
Referenced by main().
l_int32 DoComparisonDwa5 (PIX * pixs, PIX * pixt1, PIX * pixt2, PIX * pixt3, PIX * pixt4, PIX * pixt5, PIX * pixt6, l_int32 isize)
Definition at line 450 of file binmorph4_reg.c.
References pixCloseCompBrickDwa(), pixCloseSafeBrick(), PixCompareDwa(), pixDilateBrick(), pixDilateCompBrickDwa(), pixErodeBrick(), pixErodeCompBrickDwa(), pixOpenBrick(), pixOpenCompBrickDwa(), selectComposableSizes(), size, startTimer(), stopTimer(), and TIMING.
Referenced by main().
l_int32 PixCompareDwa (l_int32 size, const char * type, PIX * pixt1, PIX * pixt2, PIX * pixt3, PIX * pixt4, PIX * pixt5, PIX * pixt6)
Definition at line 522 of file binmorph4_reg.c.
References FALSE, pixEqual(), and TRUE.
Referenced by DoComparisonDwa1(), DoComparisonDwa2(), DoComparisonDwa3(), DoComparisonDwa4(), and DoComparisonDwa5().
main (int argc, char ** argv)
Definition at line 60 of file binmorph4_reg.c.
References DoComparisonDwa1(), DoComparisonDwa2(), DoComparisonDwa3(), DoComparisonDwa4(), DoComparisonDwa5(), pixAddBorder(), pixCreateTemplateNoInit(), pixDestroy(), pixRead(), pixTransferAllData(), resetMorphBoundaryCondition(), and SYMMETRIC_MORPH_BC.