Leptonica: src/binreduce.c File Reference
binreduce.c File Reference
Power of 2 integer reduction of 1 bpp images by sampling and rank value.
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "allheaders.h"
Functions
PIX * pixReduceBinary2 (PIX *pixs, l_uint8 *intab)
PIX * pixReduceRankBinaryCascade (PIX *pixs, l_int32 level1, l_int32 level2, l_int32 level3, l_int32 level4)
PIX * pixReduceRankBinary2 (PIX *pixs, l_int32 level, l_uint8 *intab)
Detailed Description
Power of 2 integer reduction of 1 bpp images by sampling and rank value.
Definition in file binreduce.c.
Function Documentation
PIX* pixReduceBinary2 (PIX * pixs, l_uint8 * intab)
pixReduceBinary2()
Input: pixs tab (<optional>; if null, a table is made here and destroyed before exit) Return: pixd (2x subsampled), or null on error
Definition at line 47 of file binreduce.c.
References ERROR_PTR, FREE, makeSubsampleTab2x(), NULL, pixCopyResolution(), pixCreate(), pixGetData(), pixGetDepth(), pixGetHeight(), pixGetWidth(), pixGetWpl(), pixScaleResolution(), PROCNAME, and reduceBinary2Low().
Referenced by main().
PIX* pixReduceRankBinaryCascade (PIX * pixs, l_int32 level1, l_int32 level2, l_int32 level3, l_int32 level4)
pixReduceRankBinaryCascade()
Input: pixs (1 bpp) level1, ... level 4 (thresholds, in the set {0, 1, 2, 3, 4}) Return: pixd, or null on error
Notes: (1) This performs up to four cascaded 2x rank reductions. (2) Use level = 0 to truncate the cascade.
Definition at line 108 of file binreduce.c.
References ERROR_PTR, FREE, L_WARNING, makeSubsampleTab2x(), NULL, pixCopy(), pixDestroy(), pixGetDepth(), pixReduceRankBinary2(), and PROCNAME.
Referenced by DoPageSegmentation(), GeneratePattern(), jbGetComponents(), main(), pixFindSkewSweep(), pixFindSkewSweepAndSearchScorePivot(), pixGenHalftoneMask(), pixGetRegionsBinary(), pixGetWordBoxesInTextlines(), pixGetWordsInTextlines(), pixMirrorDetect(), pixMirrorDetectDwa(), pixMorphCompSequence(), pixMorphCompSequenceDwa(), pixMorphSequence(), pixMorphSequenceDwa(), pixUpDownDetectGeneral(), and pixUpDownDetectGeneralDwa().
PIX* pixReduceRankBinary2 (PIX * pixs, l_int32 level, l_uint8 * intab)
pixReduceRankBinary2()
Input: pixs (1 bpp) level (rank threshold: 1, 2, 3, 4) intab (<optional>; if null, a table is made here and destroyed before exit) Return: pixd (1 bpp, 2x rank threshold reduced), or null on error
Notes: (1) pixd is downscaled by 2x from pixs. (2) The rank threshold specifies the minimum number of ON pixels in each 2x2 region of pixs that are required to set the corresponding pixel ON in pixd.
Definition at line 177 of file binreduce.c.
References ERROR_PTR, FREE, makeSubsampleTab2x(), NULL, pixCopyResolution(), pixCreate(), pixGetData(), pixGetDepth(), pixGetHeight(), pixGetWidth(), pixGetWpl(), pixScaleResolution(), PROCNAME, and reduceRankBinary2Low().
Referenced by main(), and pixReduceRankBinaryCascade().