Leptonica: prog/blend_reg.c File Reference
blend_reg.c File Reference
Regression test for pixBlendGray(), pixBlendGrayAdapt(), and pixBlendColor().
#include <stdio.h>
#include <stdlib.h>
#include "allheaders.h"
Defines
#define DISPLAY 0
Functions
void GrayBlend (PIX *pixs, PIX *pixb, l_int32 op, l_float32 fract)
void AdaptiveGrayBlend (PIX *pixs, PIX *pixb, l_float32 fract)
void ColorBlend (PIX *pixs, PIX *pixb, l_float32 fract)
PIX * MakeGrayWash (l_int32 w, l_int32 h)
PIX * MakeColorWash (l_int32 w, l_int32 h, l_int32 color)
main (int argc, char **argv)
Detailed Description
Regression test for pixBlendGray(), pixBlendGrayAdapt(), and pixBlendColor().
Definition in file blend_reg.c.
Define Documentation
#define DISPLAY 0
Definition at line 29 of file blend_reg.c.
Referenced by main().
Function Documentation
void GrayBlend (PIX * pixs, PIX * pixb, l_int32 op, l_float32 fract)
Definition at line 167 of file blend_reg.c.
References IFF_PNG, NULL, pixBlendGray(), pixDisplayWriteFormat(), and pixGetDimensions().
Referenced by main().
void AdaptiveGrayBlend (PIX * pixs, PIX * pixb, l_float32 fract)
Definition at line 196 of file blend_reg.c.
References IFF_PNG, NULL, pixBlendGrayAdapt(), pixDisplayWriteFormat(), and pixGetDimensions().
Referenced by main().
void ColorBlend (PIX * pixs, PIX * pixb, l_float32 fract)
Definition at line 224 of file blend_reg.c.
References IFF_PNG, NULL, pixBlendColor(), pixDisplayWriteFormat(), and pixGetDimensions().
Referenced by main().
PIX * MakeGrayWash (l_int32 w, l_int32 h)
Definition at line 252 of file blend_reg.c.
References pixCreate(), pixGetData(), pixGetWpl(), and SET_DATA_BYTE.
Referenced by main().
PIX * MakeColorWash (l_int32 w, l_int32 h, l_int32 color)
Definition at line 274 of file blend_reg.c.
References COLOR_GREEN, COLOR_RED, L_BLUE_SHIFT, L_GREEN_SHIFT, L_RED_SHIFT, pixCreate(), pixGetData(), and pixGetWpl().
Referenced by main().
main (int argc, char ** argv)
Definition at line 37 of file blend_reg.c.
References AdaptiveGrayBlend(), COLOR_RED, ColorBlend(), DISPLAY, GrayBlend(), IFF_JFIF_JPEG, L_BLEND_GRAY, L_BLEND_GRAY_WITH_INVERSE, MakeColorWash(), MakeGrayWash(), NULL, pixaCreate(), pixaDestroy(), pixaDisplay(), pixConvertRGBToLuminance(), pixDestroy(), pixDisplay(), pixDisplayMultiple(), pixDisplayWithTitle(), pixDisplayWrite(), pixRead(), pixRemoveColormap(), pixSaveTiled(), pixWrite(), and REMOVE_CMAP_TO_FULL_COLOR.