Leptonica: prog/ccthin1_reg.c File Reference
ccthin1_reg.c File Reference
Tests the "best" cc-preserving thinning functions. Displays all the strong cc-preserving 3x3 Sels.
#include <stdio.h>
#include <stdlib.h>
#include "allheaders.h"
Functions
main (int argc, char **argv)
Variables
static const char * sel_4_1 = " x"
static const char * sel_4_2 = " o "
static const char * sel_4_3 = " x"
static const char * sel_4_4 = " o "
static const char * sel_4_5 = " o "
static const char * sel_4_6 = " ox"
static const char * sel_4_7 = " o "
static const char * sel_4_8 = "o x"
static const char * sel_4_9 = " x"
static const char * sel_8_1 = " x "
static const char * sel_8_2 = "o "
static const char * sel_8_3 = " x "
static const char * sel_8_4 = "o "
static const char * sel_8_5 = "o "
static const char * sel_8_6 = "o x"
static const char * sel_8_7 = "oo "
static const char * sel_8_8 = "ox "
static const char * sel_8_9 = " x "
static const char * sel_48_1 = "oo "
static const char * sel_48_2 = "o x"
Detailed Description
Tests the "best" cc-preserving thinning functions. Displays all the strong cc-preserving 3x3 Sels.
Definition in file ccthin1_reg.c.
Function Documentation
main (int argc, char ** argv)
Definition at line 111 of file ccthin1_reg.c.
References boxCreate(), boxDestroy(), ERROR_INT, IFF_JFIF_JPEG, IFF_PNG, L_THIN_BG, L_THIN_FG, NULL, pixaDestroy(), pixaDisplayTiledAndScaled(), pixaReadFiles(), pixClipRectangle(), pixDestroy(), pixDisplayMultiple(), pixDisplayWrite(), pixRead(), pixThin(), pixWrite(), sel_48_1, sel_48_2, sel_4_1, sel_4_2, sel_4_3, sel_4_4, sel_4_5, sel_4_6, sel_4_7, sel_4_8, sel_4_9, sel_8_1, sel_8_2, sel_8_3, sel_8_4, sel_8_5, sel_8_6, sel_8_7, sel_8_8, sel_8_9, selaAddSel(), selaCreate(), selaDestroy(), selaDisplayInPix(), selCreateFromString(), and selRotateOrth().
Variable Documentation
const char* sel_4_1 = " x" [static]
Definition at line 28 of file ccthin1_reg.c.
Referenced by main().
const char* sel_4_2 = " o " [static]
Definition at line 32 of file ccthin1_reg.c.
Referenced by main().
const char* sel_4_3 = " x" [static]
Definition at line 36 of file ccthin1_reg.c.
Referenced by main().
const char* sel_4_4 = " o " [static]
Definition at line 40 of file ccthin1_reg.c.
Referenced by main().
const char* sel_4_5 = " o " [static]
Definition at line 44 of file ccthin1_reg.c.
Referenced by main().
const char* sel_4_6 = " ox" [static]
Definition at line 48 of file ccthin1_reg.c.
Referenced by main().
const char* sel_4_7 = " o " [static]
Definition at line 52 of file ccthin1_reg.c.
Referenced by main().
const char* sel_4_8 = "o x" [static]
Definition at line 56 of file ccthin1_reg.c.
Referenced by main().
const char* sel_4_9 = " x" [static]
Definition at line 60 of file ccthin1_reg.c.
Referenced by main().
const char* sel_8_1 = " x " [static]
Definition at line 65 of file ccthin1_reg.c.
Referenced by main().
const char* sel_8_2 = "o " [static]
Definition at line 69 of file ccthin1_reg.c.
Referenced by main().
const char* sel_8_3 = " x " [static]
Definition at line 73 of file ccthin1_reg.c.
Referenced by main().
const char* sel_8_4 = "o " [static]
Definition at line 77 of file ccthin1_reg.c.
Referenced by main().
const char* sel_8_5 = "o " [static]
Definition at line 81 of file ccthin1_reg.c.
Referenced by main().
const char* sel_8_6 = "o x" [static]
Definition at line 85 of file ccthin1_reg.c.
Referenced by main().
const char* sel_8_7 = "oo " [static]
Definition at line 89 of file ccthin1_reg.c.
Referenced by main().
const char* sel_8_8 = "ox " [static]
Definition at line 93 of file ccthin1_reg.c.
Referenced by main().
const char* sel_8_9 = " x " [static]
Definition at line 97 of file ccthin1_reg.c.
Referenced by main().
const char* sel_48_1 = "oo " [static]
Definition at line 102 of file ccthin1_reg.c.
Referenced by main().
const char* sel_48_2 = "o x" [static]
Definition at line 106 of file ccthin1_reg.c.
Referenced by main().