Leptonica: prog/colorquant_reg.c File Reference
colorquant_reg.c File Reference
Regression test for various color quantizers.
#include "allheaders.h"
Functions
static l_int32 TestImage (const char *filename, l_int32 i, L_REGPARAMS *rp)
static void PixSave32 (PIXA *pixa, PIX *pixc, L_REGPARAMS *rp)
main (int argc, char **argv)
Variables
static const l_int32 SPACE = 30
static const l_int32 MAX_WIDTH = 350
static const char * image [4]
Detailed Description
Regression test for various color quantizers.
Definition in file colorquant_reg.c.
Function Documentation
static l_int32 TestImage (const char * filename, l_int32 i, L_REGPARAMS * rp) [static]
Definition at line 55 of file colorquant_reg.c.
References buf, L_RegParams::display, ERROR_INT, FALSE, IFF_JFIF_JPEG, MAX_WIDTH, NULL, pixaCreate(), pixaDestroy(), pixaDisplay(), pixClone(), pixConvertRGBToColormap(), pixDestroy(), pixDisplayWithTitle(), pixFewColorsOctcubeQuant1(), pixFixedOctcubeQuant256(), pixFixedOctcubeQuantGenRGB(), pixGetDimensions(), pixMedianCutQuantGeneral(), pixMedianCutQuantMixed(), pixOctcubeQuantMixedWithGray(), pixOctreeColorQuant(), pixOctreeQuantByPopulation(), pixOctreeQuantNumColors(), pixRead(), pixRemoveColormap(), PixSave32(), pixSaveTiled(), pixScale(), pixWrite(), PROCNAME, REMOVE_CMAP_BASED_ON_SRC, SPACE, and L_RegParams::success.
Referenced by main().
static void PixSave32 (PIXA * pixa, PIX * pixc, L_REGPARAMS * rp) [static]
Definition at line 225 of file colorquant_reg.c.
References IFF_JFIF_JPEG, pixConvertTo32(), pixDestroy(), pixSaveTiled(), regTestWritePixAndCheck(), and SPACE.
Referenced by TestImage().
main (int argc, char ** argv)
Definition at line 35 of file colorquant_reg.c.
References image, regTestCleanup(), regTestSetup(), and TestImage().
Variable Documentation
const l_int32 SPACE = 30 [static]
Definition at line 24 of file colorquant_reg.c.
Referenced by PixSave32(), and TestImage().
const l_int32 MAX_WIDTH = 350 [static]
Definition at line 25 of file colorquant_reg.c.
Referenced by TestImage().
const char* image[4] [static]
Initial value:
 {"marge.jpg",
                               "test24.jpg",
                               "juditharismax.jpg",
                               "hardlight2_2.jpg"}
Definition at line 26 of file colorquant_reg.c.
Referenced by main(), and pixWriteTTFText().