Leptonica: src/convertfiles.c File Reference
convertfiles.c File Reference
Perform depth conversion on selected files.
#include <string.h>
#include "allheaders.h"
Functions
l_int32 convertFilesTo1bpp (const char *dirin, const char *substr, l_int32 upscaling, l_int32 thresh, l_int32 firstpage, l_int32 npages, const char *dirout, l_int32 outformat)
Detailed Description
Perform depth conversion on selected files.
Definition in file convertfiles.c.
Function Documentation
l_int32 convertFilesTo1bpp (const char * dirin, const char * substr, l_int32 upscaling, l_int32 thresh, l_int32 firstpage, l_int32 npages, const char * dirout, l_int32 outformat)
convertFilesTo1bpp()
Input: dirin substr (<optional> substring filter on filenames; can be NULL) upscaling (1, 2 or 4; only for input color or grayscale) thresh (global threshold for binarization; use 0 for default) firstpage npages (use 0 to do all from to the end) dirout outformat (IFF_PNG, IFF_TIFF_G4) Return: 0 if OK, 1 on error
Notes: (1) Images are sorted lexicographically, and the names in the output directory are retained except for the extension.
Definition at line 52 of file convertfiles.c.
References buf, ERROR_INT, FREE, getSortedPathnamesInDirectory(), IFF_PNG, IFF_TIFF_G4, L_NOCOPY, L_WARNING_STRING, nfiles, NULL, pixClone(), pixConvertRGBToLuminance(), pixDestroy(), pixGetDepth(), pixRead(), pixRemoveColormap(), pixScaleGray2xLIThresh(), pixScaleGray4xLIThresh(), pixThresholdToBinary(), pixWrite(), PROCNAME, REMOVE_CMAP_TO_GRAYSCALE, sarrayDestroy(), sarrayGetCount(), sarrayGetString(), splitPathAtDirectory(), and splitPathAtExtension().