Leptonica: prog/dewarptest.c File Reference
dewarptest.c File Reference
Demonstrates image dewarping based on text lines.
#include "allheaders.h"
Defines
#define DO_QUAD 1
#define DO_CUBIC 0
#define DO_QUARTIC 0
Functions
l_int32 main (int argc, char **argv)
Detailed Description
Demonstrates image dewarping based on text lines.
Definition in file dewarptest.c.
Define Documentation
#define DO_QUAD 1
Definition at line 26 of file dewarptest.c.
#define DO_CUBIC 0
Definition at line 27 of file dewarptest.c.
#define DO_QUARTIC 0
Definition at line 28 of file dewarptest.c.
Function Documentation
l_int32 main (int argc, char ** argv)
Definition at line 30 of file dewarptest.c.
References convertFilesToPS(), dewarpApplyDisparity(), dewarpBuildModel(), dewarpCreate(), dewarpDestroy(), IFF_JFIF_JPEG, IFF_PNG, IFF_TIFF_G4, L_CLONE, lept_mkdir(), NULL, numaDestroy(), pixBackgroundNormSimple(), pixConvertRGBToGray(), pixCreateTemplate(), pixDestroy(), pixDisplayPta(), pixDisplayPtaa(), pixDisplayWithTitle(), pixGetTextlineCenters(), pixRead(), pixThresholdToBinary(), pixWrite(), ptaaDestroy(), ptaaGetCount(), ptaaGetPta(), ptaaRemoveShortLines(), ptaCreateFromNuma(), ptaDestroy(), ptaGetArrays(), ptaGetCubicLSF(), ptaGetQuadraticLSF(), and ptaGetQuarticLSF().