Leptonica: src/dwacomblow.2.c File Reference
dwacomblow.2.c File Reference
Low-level Sel implementation for dwacomb.2.c.
#include "allheaders.h"
Functions
static void fdilate_2_0 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_0 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_2_1 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_1 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_2_2 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_2 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_2_3 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_3 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_2_4 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_4 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_2_5 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_5 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_2_6 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_6 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_2_7 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_7 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_2_8 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_8 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_2_9 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_9 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_2_10 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_10 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_2_11 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_11 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_2_12 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_12 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_2_13 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_13 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_2_14 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_14 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_2_15 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_15 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_2_16 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_16 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_2_17 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_17 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_2_18 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_18 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_2_19 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_19 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_2_20 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_20 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_2_21 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_21 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_2_22 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_22 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_2_23 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_23 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_2_24 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_24 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_2_25 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_25 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_2_26 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_26 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_2_27 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_27 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_2_28 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_28 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_2_29 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_29 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_2_30 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_30 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_2_31 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_31 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_2_32 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_32 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_2_33 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_33 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_2_34 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_34 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_2_35 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_35 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_2_36 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_36 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_2_37 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_37 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_2_38 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_38 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_2_39 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_39 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_2_40 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_40 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_2_41 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_41 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_2_42 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_42 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_2_43 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_43 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_2_44 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_44 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_2_45 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_45 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_2_46 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_46 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_2_47 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_47 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_2_48 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_48 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_2_49 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_49 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_2_50 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_50 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_2_51 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_51 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_2_52 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_52 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_2_53 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_53 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_2_54 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_54 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_2_55 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_55 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_2_56 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_56 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_2_57 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_57 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_2_58 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_58 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_2_59 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_59 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_2_60 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_60 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_2_61 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_61 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_2_62 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_62 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_2_63 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_63 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_2_64 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_64 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_2_65 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_65 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_2_66 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_66 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_2_67 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_67 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_2_68 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_68 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_2_69 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_69 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_2_70 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_70 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_2_71 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_71 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_2_72 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_72 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_2_73 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_73 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_2_74 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_74 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_2_75 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_2_75 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
l_int32 fmorphopgen_low_2 (l_uint32 *datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 *datas, l_int32 wpls, l_int32 index)
Detailed Description
Low-level Sel implementation for dwacomb.2.c.
N.B.  In all the low-level routines, the part of the image
      that is accessed has been clipped by 32 pixels on
      all four sides.  This is done in the higher level
      code by redefining w and h smaller and by moving the
      start-of-image pointers up to the beginning of this
      interior rectangle.
Definition in file dwacomblow.2.c.
Function Documentation
static void fdilate_2_0 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Low-level fast binary morphology with auto-generated sels
Dispatcher: l_int32 fmorphopgen_low_2()
Static Low-level: void fdilate_2_*() void ferode_2_*()
Definition at line 677 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_0 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 701 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void fdilate_2_1 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 725 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_1 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 749 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void fdilate_2_2 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 773 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_2 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 796 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void fdilate_2_3 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 819 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_3 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 842 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void fdilate_2_4 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 865 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_4 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 889 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void fdilate_2_5 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 913 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_5 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 939 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void fdilate_2_6 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 965 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_6 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 988 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void fdilate_2_7 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1011 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_7 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1034 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void fdilate_2_8 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1057 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_8 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1081 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void fdilate_2_9 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1105 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_9 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1131 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void fdilate_2_10 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1157 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_10 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1182 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void fdilate_2_11 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1207 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_11 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1234 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void fdilate_2_12 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1261 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_12 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1285 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void fdilate_2_13 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1309 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_13 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1337 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void fdilate_2_14 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1365 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_14 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1390 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void fdilate_2_15 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1415 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_15 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1442 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void fdilate_2_16 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1469 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_16 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1493 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void fdilate_2_17 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1517 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_17 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1545 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void fdilate_2_18 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1573 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_18 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1598 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void fdilate_2_19 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1623 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_19 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1650 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void fdilate_2_20 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1677 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_20 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1703 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void fdilate_2_21 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1729 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_21 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1759 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void fdilate_2_22 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1789 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_22 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1814 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void fdilate_2_23 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1839 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_23 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1866 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void fdilate_2_24 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1893 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_24 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1919 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void fdilate_2_25 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1945 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_25 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1979 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void fdilate_2_26 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2013 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_26 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2038 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void fdilate_2_27 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2063 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_27 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2090 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void fdilate_2_28 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2117 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_28 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2141 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void fdilate_2_29 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2165 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_29 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2193 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void fdilate_2_30 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2221 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_30 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2247 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void fdilate_2_31 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2273 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_31 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2303 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void fdilate_2_32 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2333 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_32 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2360 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void fdilate_2_33 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2387 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_33 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2418 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void fdilate_2_34 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2449 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_34 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2474 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void fdilate_2_35 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2499 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_35 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2526 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void fdilate_2_36 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2553 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_36 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2579 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void fdilate_2_37 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2605 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_37 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2639 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void fdilate_2_38 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2673 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_38 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2700 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void fdilate_2_39 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2727 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_39 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2758 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void fdilate_2_40 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2789 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_40 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2815 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void fdilate_2_41 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2841 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_41 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2871 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void fdilate_2_42 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2901 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_42 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2926 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void fdilate_2_43 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2951 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_43 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2978 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void fdilate_2_44 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 3005 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_44 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 3032 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void fdilate_2_45 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 3059 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_45 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 3090 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void fdilate_2_46 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 3121 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_46 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 3149 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void fdilate_2_47 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 3177 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_47 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 3211 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void fdilate_2_48 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 3245 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_48 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 3270 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void fdilate_2_49 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 3295 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_49 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 3322 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void fdilate_2_50 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 3349 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_50 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 3376 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void fdilate_2_51 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 3403 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_51 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 3434 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void fdilate_2_52 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 3465 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_52 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 3493 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void fdilate_2_53 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 3521 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_53 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 3561 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void fdilate_2_54 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 3601 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_54 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 3627 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void fdilate_2_55 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 3653 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_55 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 3687 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void fdilate_2_56 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 3721 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_56 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 3748 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void fdilate_2_57 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 3775 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_57 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 3806 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void fdilate_2_58 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 3837 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_58 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 3865 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void fdilate_2_59 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 3893 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_59 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 3927 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void fdilate_2_60 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 3961 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_60 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 3990 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void fdilate_2_61 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 4019 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_61 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 4054 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void fdilate_2_62 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 4089 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_62 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 4116 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void fdilate_2_63 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 4143 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_63 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 4174 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void fdilate_2_64 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 4205 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_64 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 4231 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void fdilate_2_65 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 4257 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_65 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 4291 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void fdilate_2_66 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 4325 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_66 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 4353 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void fdilate_2_67 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 4381 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_67 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 4421 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void fdilate_2_68 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 4461 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_68 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 4488 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void fdilate_2_69 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 4515 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_69 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 4546 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void fdilate_2_70 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 4577 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_70 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 4606 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void fdilate_2_71 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 4635 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_71 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 4670 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void fdilate_2_72 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 4705 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_72 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 4733 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void fdilate_2_73 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 4761 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_73 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 4795 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void fdilate_2_74 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 4829 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_74 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 4858 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void fdilate_2_75 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 4887 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
static void ferode_2_75 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 4922 of file dwacomblow.2.c.
Referenced by fmorphopgen_low_2().
l_int32 fmorphopgen_low_2 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls, l_int32 index)
fmorphopgen_low_2()
a dispatcher to appropriate low-level code
Definition at line 192 of file dwacomblow.2.c.
References fdilate_2_0(), fdilate_2_1(), fdilate_2_10(), fdilate_2_11(), fdilate_2_12(), fdilate_2_13(), fdilate_2_14(), fdilate_2_15(), fdilate_2_16(), fdilate_2_17(), fdilate_2_18(), fdilate_2_19(), fdilate_2_2(), fdilate_2_20(), fdilate_2_21(), fdilate_2_22(), fdilate_2_23(), fdilate_2_24(), fdilate_2_25(), fdilate_2_26(), fdilate_2_27(), fdilate_2_28(), fdilate_2_29(), fdilate_2_3(), fdilate_2_30(), fdilate_2_31(), fdilate_2_32(), fdilate_2_33(), fdilate_2_34(), fdilate_2_35(), fdilate_2_36(), fdilate_2_37(), fdilate_2_38(), fdilate_2_39(), fdilate_2_4(), fdilate_2_40(), fdilate_2_41(), fdilate_2_42(), fdilate_2_43(), fdilate_2_44(), fdilate_2_45(), fdilate_2_46(), fdilate_2_47(), fdilate_2_48(), fdilate_2_49(), fdilate_2_5(), fdilate_2_50(), fdilate_2_51(), fdilate_2_52(), fdilate_2_53(), fdilate_2_54(), fdilate_2_55(), fdilate_2_56(), fdilate_2_57(), fdilate_2_58(), fdilate_2_59(), fdilate_2_6(), fdilate_2_60(), fdilate_2_61(), fdilate_2_62(), fdilate_2_63(), fdilate_2_64(), fdilate_2_65(), fdilate_2_66(), fdilate_2_67(), fdilate_2_68(), fdilate_2_69(), fdilate_2_7(), fdilate_2_70(), fdilate_2_71(), fdilate_2_72(), fdilate_2_73(), fdilate_2_74(), fdilate_2_75(), fdilate_2_8(), fdilate_2_9(), ferode_2_0(), ferode_2_1(), ferode_2_10(), ferode_2_11(), ferode_2_12(), ferode_2_13(), ferode_2_14(), ferode_2_15(), ferode_2_16(), ferode_2_17(), ferode_2_18(), ferode_2_19(), ferode_2_2(), ferode_2_20(), ferode_2_21(), ferode_2_22(), ferode_2_23(), ferode_2_24(), ferode_2_25(), ferode_2_26(), ferode_2_27(), ferode_2_28(), ferode_2_29(), ferode_2_3(), ferode_2_30(), ferode_2_31(), ferode_2_32(), ferode_2_33(), ferode_2_34(), ferode_2_35(), ferode_2_36(), ferode_2_37(), ferode_2_38(), ferode_2_39(), ferode_2_4(), ferode_2_40(), ferode_2_41(), ferode_2_42(), ferode_2_43(), ferode_2_44(), ferode_2_45(), ferode_2_46(), ferode_2_47(), ferode_2_48(), ferode_2_49(), ferode_2_5(), ferode_2_50(), ferode_2_51(), ferode_2_52(), ferode_2_53(), ferode_2_54(), ferode_2_55(), ferode_2_56(), ferode_2_57(), ferode_2_58(), ferode_2_59(), ferode_2_6(), ferode_2_60(), ferode_2_61(), ferode_2_62(), ferode_2_63(), ferode_2_64(), ferode_2_65(), ferode_2_66(), ferode_2_67(), ferode_2_68(), ferode_2_69(), ferode_2_7(), ferode_2_70(), ferode_2_71(), ferode_2_72(), ferode_2_73(), ferode_2_74(), ferode_2_75(), ferode_2_8(), and ferode_2_9().
Referenced by pixFMorphopGen_2().