Leptonica: prog/dwalinearlow.3.c File Reference
dwalinearlow.3.c File Reference
Low-level fast binary morphology with auto-generated sels.
#include "allheaders.h"
Functions
static void fdilate_3_0 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_0 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_1 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_1 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_2 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_2 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_3 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_3 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_4 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_4 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_5 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_5 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_6 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_6 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_7 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_7 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_8 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_8 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_9 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_9 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_10 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_10 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_11 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_11 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_12 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_12 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_13 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_13 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_14 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_14 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_15 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_15 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_16 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_16 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_17 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_17 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_18 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_18 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_19 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_19 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_20 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_20 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_21 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_21 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_22 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_22 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_23 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_23 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_24 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_24 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_25 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_25 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_26 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_26 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_27 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_27 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_28 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_28 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_29 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_29 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_30 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_30 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_31 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_31 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_32 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_32 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_33 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_33 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_34 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_34 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_35 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_35 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_36 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_36 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_37 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_37 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_38 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_38 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_39 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_39 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_40 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_40 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_41 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_41 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_42 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_42 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_43 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_43 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_44 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_44 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_45 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_45 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_46 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_46 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_47 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_47 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_48 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_48 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_49 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_49 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_50 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_50 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_51 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_51 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_52 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_52 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_53 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_53 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_54 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_54 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_55 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_55 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_56 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_56 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_57 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_57 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_58 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_58 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_59 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_59 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_60 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_60 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_61 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_61 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_62 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_62 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_63 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_63 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_64 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_64 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_65 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_65 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_66 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_66 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_67 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_67 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_68 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_68 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_69 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_69 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_70 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_70 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_71 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_71 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_72 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_72 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_73 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_73 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_74 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_74 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_75 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_75 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_76 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_76 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_77 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_77 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_78 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_78 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_79 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_79 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_80 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_80 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_81 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_81 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_82 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_82 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_83 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_83 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_84 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_84 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_85 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_85 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_86 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_86 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_87 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_87 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_88 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_88 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_89 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_89 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_90 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_90 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_91 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_91 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_92 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_92 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_93 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_93 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_94 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_94 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_95 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_95 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_96 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_96 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_97 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_97 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_98 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_98 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_99 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_99 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_100 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_100 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_101 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_101 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_102 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_102 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_103 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_103 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_104 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_104 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_105 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_105 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_106 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_106 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_107 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_107 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_108 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_108 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_109 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_109 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_110 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_110 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_111 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_111 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_112 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_112 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_113 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_113 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_114 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_114 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_115 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_115 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_116 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_116 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_117 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_117 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_118 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_118 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_119 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_119 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_120 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_120 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_121 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_121 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_122 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_122 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_3_123 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_3_123 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
l_int32 fmorphopgen_low_3 (l_uint32 *datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 *datas, l_int32 wpls, l_int32 index)
Detailed Description
Low-level fast binary morphology with auto-generated sels.
Definition in file dwalinearlow.3.c.
Function Documentation
static void fdilate_3_0 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Low-level fast binary morphology with auto-generated sels
Dispatcher: l_int32 fmorphopgen_low_3()
Static Low-level: void fdilate_3_*() void ferode_3_*()
Definition at line 1061 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_0 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1085 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_1 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1109 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_1 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1134 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_2 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1159 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_2 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1185 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_3 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1211 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_3 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1238 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_4 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1265 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_4 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1293 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_5 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1321 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_5 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1350 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_6 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1379 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_6 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1409 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_7 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1439 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_7 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1470 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_8 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1501 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_8 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1533 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_9 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1565 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_9 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1598 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_10 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1631 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_10 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1665 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_11 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1699 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_11 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1734 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_12 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1769 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_12 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1805 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_13 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1841 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_13 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1878 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_14 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1915 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_14 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1953 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_15 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1991 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_15 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2030 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_16 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2069 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_16 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2109 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_17 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2149 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_17 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2190 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_18 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2231 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_18 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2273 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_19 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2315 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_19 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2358 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_20 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2401 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_20 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2445 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_21 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2489 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_21 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2534 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_22 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2579 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_22 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2625 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_23 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2671 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_23 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2718 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_24 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2765 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_24 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2813 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_25 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2861 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_25 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2910 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_26 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2959 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_26 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 3009 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_27 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 3059 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_27 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 3110 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_28 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 3161 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_28 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 3213 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_29 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 3265 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_29 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 3318 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_30 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 3371 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_30 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 3425 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_31 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 3479 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_31 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 3534 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_32 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 3589 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_32 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 3645 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_33 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 3701 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_33 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 3758 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_34 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 3815 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_34 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 3873 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_35 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 3931 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_35 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 3990 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_36 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 4049 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_36 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 4109 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_37 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 4169 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_37 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 4230 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_38 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 4291 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_38 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 4353 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_39 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 4415 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_39 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 4478 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_40 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 4541 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_40 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 4605 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_41 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 4669 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_41 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 4734 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_42 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 4799 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_42 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 4865 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_43 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 4931 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_43 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 4998 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_44 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 5065 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_44 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 5133 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_45 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 5201 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_45 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 5270 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_46 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 5339 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_46 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 5409 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_47 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 5479 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_47 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 5550 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_48 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 5621 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_48 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 5693 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_49 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 5765 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_49 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 5838 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_50 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 5911 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_50 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 5985 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_51 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 6059 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_51 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 6134 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_52 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 6209 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_52 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 6285 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_53 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 6361 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_53 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 6438 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_54 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 6515 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_54 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 6593 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_55 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 6671 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_55 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 6750 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_56 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 6829 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_56 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 6909 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_57 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 6989 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_57 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 7070 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_58 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 7151 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_58 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 7233 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_59 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 7315 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_59 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 7398 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_60 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 7481 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_60 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 7565 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_61 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 7649 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_61 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 7734 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_62 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 7819 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_62 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 7843 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_63 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 7867 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_63 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 7892 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_64 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 7917 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_64 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 7945 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_65 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 7973 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_65 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 8002 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_66 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 8031 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_66 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 8062 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_67 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 8093 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_67 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 8125 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_68 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 8157 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_68 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 8191 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_69 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 8225 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_69 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 8260 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_70 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 8295 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_70 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 8333 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_71 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 8371 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_71 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 8410 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_72 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 8449 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_72 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 8490 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_73 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 8531 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_73 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 8573 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_74 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 8615 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_74 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 8659 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_75 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 8703 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_75 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 8748 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_76 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 8793 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_76 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 8840 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_77 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 8887 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_77 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 8935 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_78 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 8983 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_78 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 9034 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_79 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 9085 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_79 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 9137 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_80 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 9189 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_80 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 9243 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_81 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 9297 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_81 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 9352 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_82 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 9407 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_82 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 9464 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_83 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 9521 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_83 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 9579 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_84 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 9637 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_84 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 9697 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_85 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 9757 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_85 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 9818 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_86 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 9879 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_86 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 9943 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_87 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 10007 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_87 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 10072 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_88 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 10137 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_88 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 10204 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_89 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 10271 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_89 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 10339 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_90 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 10407 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_90 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 10477 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_91 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 10547 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_91 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 10618 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_92 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 10689 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_92 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 10762 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_93 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 10835 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_93 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 10909 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_94 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 10983 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_94 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 11060 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_95 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 11137 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_95 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 11215 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_96 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 11293 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_96 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 11373 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_97 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 11453 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_97 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 11534 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_98 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 11615 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_98 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 11698 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_99 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 11781 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_99 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 11865 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_100 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 11949 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_100 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 12035 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_101 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 12121 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_101 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 12208 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_102 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 12295 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_102 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 12385 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_103 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 12475 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_103 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 12566 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_104 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 12657 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_104 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 12750 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_105 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 12843 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_105 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 12937 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_106 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 13031 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_106 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 13127 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_107 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 13223 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_107 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 13320 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_108 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 13417 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_108 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 13516 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_109 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 13615 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_109 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 13715 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_110 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 13815 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_110 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 13918 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_111 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 14021 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_111 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 14125 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_112 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 14229 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_112 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 14335 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_113 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 14441 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_113 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 14548 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_114 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 14655 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_114 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 14764 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_115 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 14873 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_115 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 14983 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_116 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 15093 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_116 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 15205 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_117 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 15317 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_117 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 15430 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_118 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 15543 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_118 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 15659 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_119 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 15775 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_119 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 15892 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_120 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 16009 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_120 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 16128 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_121 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 16247 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_121 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 16367 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_122 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 16487 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_122 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 16609 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void fdilate_3_123 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 16731 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
static void ferode_3_123 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 16854 of file dwalinearlow.3.c.
Referenced by fmorphopgen_low_3().
l_int32 fmorphopgen_low_3 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls, l_int32 index)
fmorphopgen_low_3()
a dispatcher to appropriate low-level code
Definition at line 288 of file dwalinearlow.3.c.
References fdilate_3_0(), fdilate_3_1(), fdilate_3_10(), fdilate_3_100(), fdilate_3_101(), fdilate_3_102(), fdilate_3_103(), fdilate_3_104(), fdilate_3_105(), fdilate_3_106(), fdilate_3_107(), fdilate_3_108(), fdilate_3_109(), fdilate_3_11(), fdilate_3_110(), fdilate_3_111(), fdilate_3_112(), fdilate_3_113(), fdilate_3_114(), fdilate_3_115(), fdilate_3_116(), fdilate_3_117(), fdilate_3_118(), fdilate_3_119(), fdilate_3_12(), fdilate_3_120(), fdilate_3_121(), fdilate_3_122(), fdilate_3_123(), fdilate_3_13(), fdilate_3_14(), fdilate_3_15(), fdilate_3_16(), fdilate_3_17(), fdilate_3_18(), fdilate_3_19(), fdilate_3_2(), fdilate_3_20(), fdilate_3_21(), fdilate_3_22(), fdilate_3_23(), fdilate_3_24(), fdilate_3_25(), fdilate_3_26(), fdilate_3_27(), fdilate_3_28(), fdilate_3_29(), fdilate_3_3(), fdilate_3_30(), fdilate_3_31(), fdilate_3_32(), fdilate_3_33(), fdilate_3_34(), fdilate_3_35(), fdilate_3_36(), fdilate_3_37(), fdilate_3_38(), fdilate_3_39(), fdilate_3_4(), fdilate_3_40(), fdilate_3_41(), fdilate_3_42(), fdilate_3_43(), fdilate_3_44(), fdilate_3_45(), fdilate_3_46(), fdilate_3_47(), fdilate_3_48(), fdilate_3_49(), fdilate_3_5(), fdilate_3_50(), fdilate_3_51(), fdilate_3_52(), fdilate_3_53(), fdilate_3_54(), fdilate_3_55(), fdilate_3_56(), fdilate_3_57(), fdilate_3_58(), fdilate_3_59(), fdilate_3_6(), fdilate_3_60(), fdilate_3_61(), fdilate_3_62(), fdilate_3_63(), fdilate_3_64(), fdilate_3_65(), fdilate_3_66(), fdilate_3_67(), fdilate_3_68(), fdilate_3_69(), fdilate_3_7(), fdilate_3_70(), fdilate_3_71(), fdilate_3_72(), fdilate_3_73(), fdilate_3_74(), fdilate_3_75(), fdilate_3_76(), fdilate_3_77(), fdilate_3_78(), fdilate_3_79(), fdilate_3_8(), fdilate_3_80(), fdilate_3_81(), fdilate_3_82(), fdilate_3_83(), fdilate_3_84(), fdilate_3_85(), fdilate_3_86(), fdilate_3_87(), fdilate_3_88(), fdilate_3_89(), fdilate_3_9(), fdilate_3_90(), fdilate_3_91(), fdilate_3_92(), fdilate_3_93(), fdilate_3_94(), fdilate_3_95(), fdilate_3_96(), fdilate_3_97(), fdilate_3_98(), fdilate_3_99(), ferode_3_0(), ferode_3_1(), ferode_3_10(), ferode_3_100(), ferode_3_101(), ferode_3_102(), ferode_3_103(), ferode_3_104(), ferode_3_105(), ferode_3_106(), ferode_3_107(), ferode_3_108(), ferode_3_109(), ferode_3_11(), ferode_3_110(), ferode_3_111(), ferode_3_112(), ferode_3_113(), ferode_3_114(), ferode_3_115(), ferode_3_116(), ferode_3_117(), ferode_3_118(), ferode_3_119(), ferode_3_12(), ferode_3_120(), ferode_3_121(), ferode_3_122(), ferode_3_123(), ferode_3_13(), ferode_3_14(), ferode_3_15(), ferode_3_16(), ferode_3_17(), ferode_3_18(), ferode_3_19(), ferode_3_2(), ferode_3_20(), ferode_3_21(), ferode_3_22(), ferode_3_23(), ferode_3_24(), ferode_3_25(), ferode_3_26(), ferode_3_27(), ferode_3_28(), ferode_3_29(), ferode_3_3(), ferode_3_30(), ferode_3_31(), ferode_3_32(), ferode_3_33(), ferode_3_34(), ferode_3_35(), ferode_3_36(), ferode_3_37(), ferode_3_38(), ferode_3_39(), ferode_3_4(), ferode_3_40(), ferode_3_41(), ferode_3_42(), ferode_3_43(), ferode_3_44(), ferode_3_45(), ferode_3_46(), ferode_3_47(), ferode_3_48(), ferode_3_49(), ferode_3_5(), ferode_3_50(), ferode_3_51(), ferode_3_52(), ferode_3_53(), ferode_3_54(), ferode_3_55(), ferode_3_56(), ferode_3_57(), ferode_3_58(), ferode_3_59(), ferode_3_6(), ferode_3_60(), ferode_3_61(), ferode_3_62(), ferode_3_63(), ferode_3_64(), ferode_3_65(), ferode_3_66(), ferode_3_67(), ferode_3_68(), ferode_3_69(), ferode_3_7(), ferode_3_70(), ferode_3_71(), ferode_3_72(), ferode_3_73(), ferode_3_74(), ferode_3_75(), ferode_3_76(), ferode_3_77(), ferode_3_78(), ferode_3_79(), ferode_3_8(), ferode_3_80(), ferode_3_81(), ferode_3_82(), ferode_3_83(), ferode_3_84(), ferode_3_85(), ferode_3_86(), ferode_3_87(), ferode_3_88(), ferode_3_89(), ferode_3_9(), ferode_3_90(), ferode_3_91(), ferode_3_92(), ferode_3_93(), ferode_3_94(), ferode_3_95(), ferode_3_96(), ferode_3_97(), ferode_3_98(), and ferode_3_99().
Referenced by pixFMorphopGen_3().