Leptonica: prog/dwamorph2_reg.c File Reference
dwamorph2_reg.c File Reference
Fairly thorough regression test for autogen'd dwa.
#include "allheaders.h"
Defines
#define HALFWIDTH 3
Functions
PIX * pixMorphDwa_3 (PIX *pixd, PIX *pixs, l_int32 operation, char *selname)
main (int argc, char **argv)
Variables
static const l_int32 NTIMES = 20
Detailed Description
Fairly thorough regression test for autogen'd dwa.
Definition in file dwamorph2_reg.c.
Define Documentation
#define HALFWIDTH 3
Definition at line 24 of file dwamorph2_reg.c.
Referenced by main().
Function Documentation
PIX* pixMorphDwa_3 (PIX * pixd, PIX * pixs, l_int32 operation, char * selname)
Top-level fast binary morphology with auto-generated sels
PIX *pixMorphDwa_3() PIX *pixFMorphopGen_3()
pixMorphDwa_3()
Input: pixd (usual 3 choices: null, == pixs, != pixs) pixs (1 bpp) operation (L_MORPH_DILATE, L_MORPH_ERODE, L_MORPH_OPEN, L_MORPH_CLOSE) sel name Return: pixd
Notes: (1) This simply adds a border, calls the appropriate pixFMorphopGen_*(), and removes the border. See the notes for that function. (2) The size of the border depends on the operation and the boundary conditions.
Definition at line 178 of file dwalinear.3.c.
References ERROR_PTR, getMorphBorderPixelColor(), L_MORPH_CLOSE, L_MORPH_ERODE, NULL, pixAddBorder(), pixCopy(), pixDestroy(), pixFMorphopGen_3(), pixGetDepth(), pixRemoveBorder(), and PROCNAME.
Referenced by main().
main (int argc, char ** argv)
Definition at line 31 of file dwamorph2_reg.c.
References ERROR_INT, GPLOT_LINES, GPLOT_PNG, gplotAddPlot(), gplotCreate(), gplotDestroy(), gplotMakeOutput(), HALFWIDTH, IFF_PNG, L_INSERT, L_MORPH_CLOSE, L_MORPH_DILATE, L_MORPH_ERODE, L_MORPH_OPEN, NTIMES, NULL, numaAddNumber(), numaCreate(), numaDestroy(), numaEmpty(), numaMakeSequence(), numaWindowedMean(), pixaAddPix(), pixaCreate(), pixaDestroy(), pixaDisplayTiledInRows(), pixClose(), pixCloseCompBrick(), pixCloseCompBrickDwa(), pixCreateTemplate(), pixDestroy(), pixDilate(), pixDilateCompBrick(), pixDilateCompBrickDwa(), pixDisplay(), pixErode(), pixErodeCompBrick(), pixErodeCompBrickDwa(), pixMorphDwa_3(), pixOpen(), pixOpenCompBrick(), pixOpenCompBrickDwa(), pixRead(), pixWrite(), selaAddDwaLinear(), selaDestroy(), selaGetCount(), selaGetSel(), selGetName(), selGetParameters(), startTimer(), and stopTimer().
Variable Documentation
const l_int32 NTIMES = 20 [static]
Definition at line 29 of file dwamorph2_reg.c.
Referenced by main().