Leptonica: prog/expand_reg.c File Reference
expand_reg.c File Reference
Tests of various image expansion techniques.
#include <stdio.h>
#include <stdlib.h>
#include "allheaders.h"
Defines
#define BINARY_IMAGE "test1.png"
#define TWO_BPP_IMAGE_NO_CMAP "weasel2.4g.png"
#define TWO_BPP_IMAGE_CMAP "weasel2.4c.png"
#define FOUR_BPP_IMAGE_NO_CMAP "weasel4.16g.png"
#define FOUR_BPP_IMAGE_CMAP "weasel4.16c.png"
#define EIGHT_BPP_IMAGE_NO_CMAP "weasel8.149g.png"
#define EIGHT_BPP_IMAGE_CMAP "weasel8.240c.png"
#define RGB_IMAGE "marge.jpg"
Functions
main (int argc, char **argv)
Detailed Description
Tests of various image expansion techniques.
Definition in file expand_reg.c.
Define Documentation
#define BINARY_IMAGE "test1.png"
Definition at line 25 of file expand_reg.c.
Referenced by main().
#define TWO_BPP_IMAGE_NO_CMAP "weasel2.4g.png"
Definition at line 26 of file expand_reg.c.
Referenced by main().
#define TWO_BPP_IMAGE_CMAP "weasel2.4c.png"
Definition at line 27 of file expand_reg.c.
Referenced by main().
#define FOUR_BPP_IMAGE_NO_CMAP "weasel4.16g.png"
Definition at line 28 of file expand_reg.c.
Referenced by main().
#define FOUR_BPP_IMAGE_CMAP "weasel4.16c.png"
Definition at line 29 of file expand_reg.c.
Referenced by main().
#define EIGHT_BPP_IMAGE_NO_CMAP "weasel8.149g.png"
Definition at line 30 of file expand_reg.c.
Referenced by main().
#define EIGHT_BPP_IMAGE_CMAP "weasel8.240c.png"
Definition at line 31 of file expand_reg.c.
Referenced by main().
#define RGB_IMAGE "marge.jpg"
Definition at line 32 of file expand_reg.c.
Referenced by main().
Function Documentation
main (int argc, char ** argv)
Definition at line 35 of file expand_reg.c.
References BINARY_IMAGE, boxCreate(), boxDestroy(), EIGHT_BPP_IMAGE_CMAP, EIGHT_BPP_IMAGE_NO_CMAP, ERROR_INT, FALSE, filename, FOUR_BPP_IMAGE_CMAP, FOUR_BPP_IMAGE_NO_CMAP, IFF_PNG, NULL, pixClipRectangle(), pixConvert1To2(), pixConvert1To4(), pixConvertTo8(), pixDestroy(), pixDisplayMultiple(), pixDisplayWrite(), pixEqual(), pixExpandBinaryPower2(), pixExpandReplicate(), pixGetDimensions(), pixRead(), pixReduceRankBinary2(), pixReduceRankBinaryCascade(), pixScale(), pixThresholdToBinary(), pixWrite(), RGB_IMAGE, TWO_BPP_IMAGE_CMAP, and TWO_BPP_IMAGE_NO_CMAP.