Leptonica: src/fhmtgenlow.1.c File Reference
fhmtgenlow.1.c File Reference
Low-level Sel implementation for fhmtgen.1.c.
#include "allheaders.h"
Functions
static void fhmt_1_0 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fhmt_1_1 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fhmt_1_2 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fhmt_1_3 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fhmt_1_4 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fhmt_1_5 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
l_int32 fhmtgen_low_1 (l_uint32 *datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 *datas, l_int32 wpls, l_int32 index)
Detailed Description
Low-level Sel implementation for fhmtgen.1.c.
N.B.  In all the low-level routines, the part of the image
      that is accessed has been clipped by 32 pixels on
      all four sides.  This is done in the higher level
      code by redefining w and h smaller and by moving the
      start-of-image pointers up to the beginning of this
      interior rectangle.
Definition in file fhmtgenlow.1.c.
Function Documentation
static void fhmt_1_0 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Low-level fast hit-miss transform with auto-generated sels
Dispatcher: l_int32 fhmtgen_low_1()
Static Low-level: void fhmt_1_*()
Definition at line 92 of file fhmtgenlow.1.c.
Referenced by fhmtgen_low_1().
static void fhmt_1_1 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 123 of file fhmtgenlow.1.c.
Referenced by fhmtgen_low_1().
static void fhmt_1_2 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 151 of file fhmtgenlow.1.c.
Referenced by fhmtgen_low_1().
static void fhmt_1_3 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 179 of file fhmtgenlow.1.c.
Referenced by fhmtgen_low_1().
static void fhmt_1_4 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 207 of file fhmtgenlow.1.c.
Referenced by fhmtgen_low_1().
static void fhmt_1_5 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 235 of file fhmtgenlow.1.c.
Referenced by fhmtgen_low_1().
l_int32 fhmtgen_low_1 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls, l_int32 index)
fhmtgen_low_1()
a dispatcher to appropriate low-level code
Definition at line 45 of file fhmtgenlow.1.c.
References fhmt_1_0(), fhmt_1_1(), fhmt_1_2(), fhmt_1_3(), fhmt_1_4(), and fhmt_1_5().
Referenced by pixFHMTGen_1().