Leptonica: prog/findpattern3.c File Reference
findpattern3.c File Reference
Demonstrates generating a hit-miss sel by extracting the letter "c" and the word "Caltech" from feyn.tif and using pixGenerateSelBoundary().
#include <stdio.h>
#include <stdlib.h>
#include "allheaders.h"
Functions
main (int argc, char **argv)
Variables
static const l_uint32 HitColor = 0x33aa4400
static const l_uint32 MissColor = 0xaa44bb00
Detailed Description
Demonstrates generating a hit-miss sel by extracting the letter "c" and the word "Caltech" from feyn.tif and using pixGenerateSelBoundary().
Definition in file findpattern3.c.
Function Documentation
main (int argc, char ** argv)
Definition at line 41 of file findpattern3.c.
References boxCreate(), boxDestroy(), Sel::cx, Sel::cy, ERROR_INT, HitColor, IFF_PNG, MissColor, NULL, pixClipRectangle(), pixCopy(), pixDestroy(), pixDisplay(), pixDisplayHitMissSel(), pixDisplayMatchedPattern(), pixGenerateSelBoundary(), pixHMT(), pixRead(), pixRemoveMatchedPattern(), pixWrite(), selDestroy(), startTimer(), and stopTimer().
Variable Documentation
const l_uint32 HitColor = 0x33aa4400 [static]
Definition at line 37 of file findpattern3.c.
Referenced by main().
const l_uint32 MissColor = 0xaa44bb00 [static]
Definition at line 38 of file findpattern3.c.
Referenced by main().