Leptonica: src/fliphmtgen.c File Reference
fliphmtgen.c File Reference
Hit-miss transforms for flipdetect.c.
#include <stdio.h>
#include <string.h>
#include "allheaders.h"
Functions
static l_int32 flipfhmtgen_low (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32, l_int32)
static void fhmt_1_0 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fhmt_1_1 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fhmt_1_2 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fhmt_1_3 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
PIX * pixFlipFHMTGen (PIX *pixd, PIX *pixs, char *selname)
Variables
static l_int32 NUM_SELS_GENERATED = 4
static char SEL_NAMES [][10]
Detailed Description
Hit-miss transforms for flipdetect.c.
     DWA implementation of hit-miss transforms with auto-generated sels
     for pixOrientDetectDwa() and pixUpDownDetectDwa() in flipdetect.c
          PIX             *pixFlipFHMTGen()
            static l_int32   flipfhmtgen_low()  -- dispatcher
              static void      fhmt_1_0()
              static void      fhmt_1_1()
              static void      fhmt_1_2()
              static void      fhmt_1_3()
     The code (rearranged) was generated by prog/flipselgen.c
Definition in file fliphmtgen.c.
Function Documentation
static l_int32 flipfhmtgen_low (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls, l_int32 index) [static]
Definition at line 137 of file fliphmtgen.c.
References fhmt_1_0(), fhmt_1_1(), fhmt_1_2(), and fhmt_1_3().
Referenced by pixFlipFHMTGen().
static void fhmt_1_0 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 179 of file fliphmtgen.c.
Referenced by flipfhmtgen_low().
static void fhmt_1_1 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 221 of file fliphmtgen.c.
Referenced by flipfhmtgen_low().
static void fhmt_1_2 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 263 of file fliphmtgen.c.
Referenced by flipfhmtgen_low().
static void fhmt_1_3 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 305 of file fliphmtgen.c.
Referenced by flipfhmtgen_low().
PIX* pixFlipFHMTGen (PIX * pixd, PIX * pixs, char * selname)
Definition at line 66 of file fliphmtgen.c.
References ADDED_BORDER, ERROR_PTR, FALSE, flipfhmtgen_low(), NULL, NUM_SELS_GENERATED, pixCopy(), pixCreateTemplate(), L_Dewarp::pixd, pixDestroy(), pixGetData(), pixGetDepth(), pixGetHeight(), pixGetWidth(), pixGetWpl(), pixSizesEqual(), PROCNAME, SEL_NAMES, and TRUE.
Referenced by pixMirrorDetectDwa(), and pixUpDownDetectGeneralDwa().
Variable Documentation
l_int32 NUM_SELS_GENERATED = 4 [static]
Definition at line 36 of file fliphmtgen.c.
Referenced by pixFlipFHMTGen().
char SEL_NAMES[][10] [static]
Initial value:
 {"flipsel1",
                                "flipsel2",
                                "flipsel3",
                                "flipsel4"}
Definition at line 37 of file fliphmtgen.c.
Referenced by pixFlipFHMTGen().