Leptonica: src/fmorphgenlow.1.c File Reference
fmorphgenlow.1.c File Reference
Low-level Sel implementation for fmorphgen.1.c.
#include "allheaders.h"
Functions
static void fdilate_1_0 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_1_0 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_1_1 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_1_1 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_1_2 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_1_2 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_1_3 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_1_3 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_1_4 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_1_4 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_1_5 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_1_5 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_1_6 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_1_6 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_1_7 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_1_7 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_1_8 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_1_8 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_1_9 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_1_9 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_1_10 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_1_10 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_1_11 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_1_11 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_1_12 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_1_12 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_1_13 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_1_13 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_1_14 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_1_14 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_1_15 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_1_15 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_1_16 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_1_16 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_1_17 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_1_17 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_1_18 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_1_18 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_1_19 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_1_19 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_1_20 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_1_20 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_1_21 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_1_21 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_1_22 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_1_22 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_1_23 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_1_23 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_1_24 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_1_24 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_1_25 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_1_25 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_1_26 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_1_26 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_1_27 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_1_27 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_1_28 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_1_28 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_1_29 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_1_29 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_1_30 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_1_30 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_1_31 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_1_31 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_1_32 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_1_32 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_1_33 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_1_33 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_1_34 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_1_34 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_1_35 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_1_35 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_1_36 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_1_36 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_1_37 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_1_37 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_1_38 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_1_38 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_1_39 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_1_39 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_1_40 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_1_40 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_1_41 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_1_41 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_1_42 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_1_42 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_1_43 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_1_43 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_1_44 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_1_44 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_1_45 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_1_45 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_1_46 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_1_46 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_1_47 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_1_47 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_1_48 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_1_48 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_1_49 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_1_49 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_1_50 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_1_50 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_1_51 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_1_51 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_1_52 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_1_52 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_1_53 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_1_53 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_1_54 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_1_54 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_1_55 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_1_55 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_1_56 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_1_56 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void fdilate_1_57 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
static void ferode_1_57 (l_uint32 *, l_int32, l_int32, l_int32, l_uint32 *, l_int32)
l_int32 fmorphopgen_low_1 (l_uint32 *datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 *datas, l_int32 wpls, l_int32 index)
Detailed Description
Low-level Sel implementation for fmorphgen.1.c.
Definition in file fmorphgenlow.1.c.
Function Documentation
static void fdilate_1_0 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Low-level fast binary morphology with auto-generated sels
Dispatcher: l_int32 fmorphopgen_low_1()
Static Low-level: void fdilate_1_*() void ferode_1_*()
Definition at line 533 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void ferode_1_0 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 557 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void fdilate_1_1 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 581 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void ferode_1_1 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 606 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void fdilate_1_2 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 631 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void ferode_1_2 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 657 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void fdilate_1_3 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 683 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void ferode_1_3 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 710 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void fdilate_1_4 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 737 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void ferode_1_4 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 765 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void fdilate_1_5 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 793 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void ferode_1_5 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 822 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void fdilate_1_6 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 851 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void ferode_1_6 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 881 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void fdilate_1_7 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 911 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void ferode_1_7 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 942 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void fdilate_1_8 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 973 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void ferode_1_8 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1005 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void fdilate_1_9 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1037 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void ferode_1_9 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1070 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void fdilate_1_10 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1103 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void ferode_1_10 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1137 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void fdilate_1_11 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1171 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void ferode_1_11 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1206 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void fdilate_1_12 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1241 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void ferode_1_12 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1277 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void fdilate_1_13 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1313 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void ferode_1_13 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1350 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void fdilate_1_14 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1387 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void ferode_1_14 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1429 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void fdilate_1_15 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1471 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void ferode_1_15 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1514 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void fdilate_1_16 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1557 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void ferode_1_16 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1604 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void fdilate_1_17 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1651 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void ferode_1_17 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1703 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void fdilate_1_18 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1755 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void ferode_1_18 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1808 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void fdilate_1_19 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1861 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void ferode_1_19 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1918 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void fdilate_1_20 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 1975 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void ferode_1_20 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2037 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void fdilate_1_21 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2099 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void ferode_1_21 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2162 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void fdilate_1_22 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2225 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void ferode_1_22 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2292 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void fdilate_1_23 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2359 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void ferode_1_23 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2431 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void fdilate_1_24 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2503 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void ferode_1_24 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2576 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void fdilate_1_25 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2649 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void ferode_1_25 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2673 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void fdilate_1_26 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2697 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void ferode_1_26 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2722 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void fdilate_1_27 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2747 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void ferode_1_27 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2775 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void fdilate_1_28 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2803 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void ferode_1_28 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2832 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void fdilate_1_29 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2861 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void ferode_1_29 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2892 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void fdilate_1_30 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2923 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void ferode_1_30 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2955 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void fdilate_1_31 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 2987 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void ferode_1_31 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 3021 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void fdilate_1_32 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 3055 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void ferode_1_32 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 3090 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void fdilate_1_33 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 3125 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void ferode_1_33 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 3163 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void fdilate_1_34 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 3201 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void ferode_1_34 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 3240 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void fdilate_1_35 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 3279 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void ferode_1_35 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 3320 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void fdilate_1_36 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 3361 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void ferode_1_36 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 3403 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void fdilate_1_37 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 3445 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void ferode_1_37 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 3489 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void fdilate_1_38 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 3533 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void ferode_1_38 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 3578 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void fdilate_1_39 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 3623 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void ferode_1_39 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 3677 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void fdilate_1_40 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 3731 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void ferode_1_40 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 3786 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void fdilate_1_41 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 3841 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void ferode_1_41 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 3902 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void fdilate_1_42 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 3963 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void ferode_1_42 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 4033 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void fdilate_1_43 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 4103 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void ferode_1_43 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 4174 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void fdilate_1_44 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 4245 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void ferode_1_44 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 4323 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void fdilate_1_45 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 4401 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void ferode_1_45 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 4487 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void fdilate_1_46 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 4573 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void ferode_1_46 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 4660 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void fdilate_1_47 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 4747 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void ferode_1_47 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 4841 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void fdilate_1_48 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 4935 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void ferode_1_48 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 5038 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void fdilate_1_49 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 5141 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void ferode_1_49 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 5245 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void fdilate_1_50 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 5349 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void ferode_1_50 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 5375 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void fdilate_1_51 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 5401 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void ferode_1_51 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 5432 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void fdilate_1_52 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 5463 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void ferode_1_52 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 5503 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void fdilate_1_53 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 5543 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void ferode_1_53 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 5592 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void fdilate_1_54 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 5641 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void ferode_1_54 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 5665 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void fdilate_1_55 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 5689 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void ferode_1_55 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 5713 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void fdilate_1_56 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 5737 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void ferode_1_56 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 5766 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void fdilate_1_57 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 5795 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
static void ferode_1_57 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls) [static]
Definition at line 5824 of file fmorphgenlow.1.c.
Referenced by fmorphopgen_low_1().
l_int32 fmorphopgen_low_1 (l_uint32 * datad, l_int32 w, l_int32 h, l_int32 wpld, l_uint32 * datas, l_int32 wpls, l_int32 index)
fmorphopgen_low_1()
a dispatcher to appropriate low-level code
Definition at line 156 of file fmorphgenlow.1.c.
References fdilate_1_0(), fdilate_1_1(), fdilate_1_10(), fdilate_1_11(), fdilate_1_12(), fdilate_1_13(), fdilate_1_14(), fdilate_1_15(), fdilate_1_16(), fdilate_1_17(), fdilate_1_18(), fdilate_1_19(), fdilate_1_2(), fdilate_1_20(), fdilate_1_21(), fdilate_1_22(), fdilate_1_23(), fdilate_1_24(), fdilate_1_25(), fdilate_1_26(), fdilate_1_27(), fdilate_1_28(), fdilate_1_29(), fdilate_1_3(), fdilate_1_30(), fdilate_1_31(), fdilate_1_32(), fdilate_1_33(), fdilate_1_34(), fdilate_1_35(), fdilate_1_36(), fdilate_1_37(), fdilate_1_38(), fdilate_1_39(), fdilate_1_4(), fdilate_1_40(), fdilate_1_41(), fdilate_1_42(), fdilate_1_43(), fdilate_1_44(), fdilate_1_45(), fdilate_1_46(), fdilate_1_47(), fdilate_1_48(), fdilate_1_49(), fdilate_1_5(), fdilate_1_50(), fdilate_1_51(), fdilate_1_52(), fdilate_1_53(), fdilate_1_54(), fdilate_1_55(), fdilate_1_56(), fdilate_1_57(), fdilate_1_6(), fdilate_1_7(), fdilate_1_8(), fdilate_1_9(), ferode_1_0(), ferode_1_1(), ferode_1_10(), ferode_1_11(), ferode_1_12(), ferode_1_13(), ferode_1_14(), ferode_1_15(), ferode_1_16(), ferode_1_17(), ferode_1_18(), ferode_1_19(), ferode_1_2(), ferode_1_20(), ferode_1_21(), ferode_1_22(), ferode_1_23(), ferode_1_24(), ferode_1_25(), ferode_1_26(), ferode_1_27(), ferode_1_28(), ferode_1_29(), ferode_1_3(), ferode_1_30(), ferode_1_31(), ferode_1_32(), ferode_1_33(), ferode_1_34(), ferode_1_35(), ferode_1_36(), ferode_1_37(), ferode_1_38(), ferode_1_39(), ferode_1_4(), ferode_1_40(), ferode_1_41(), ferode_1_42(), ferode_1_43(), ferode_1_44(), ferode_1_45(), ferode_1_46(), ferode_1_47(), ferode_1_48(), ferode_1_49(), ferode_1_5(), ferode_1_50(), ferode_1_51(), ferode_1_52(), ferode_1_53(), ferode_1_54(), ferode_1_55(), ferode_1_56(), ferode_1_57(), ferode_1_6(), ferode_1_7(), ferode_1_8(), and ferode_1_9().
Referenced by pixFMorphopGen_1().