Leptonica: prog/gammatest.c File Reference
gammatest.c File Reference
Exploration of gamma adjustment using pixGammaTRC() and numaGammaTRC().
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include "allheaders.h"
Defines
#define NPLOTS 5
#define MINVAL 30
#define MAXVAL 210
Functions
main (int argc, char **argv)
Detailed Description
Exploration of gamma adjustment using pixGammaTRC() and numaGammaTRC().
Definition in file gammatest.c.
Define Documentation
#define NPLOTS 5
Definition at line 26 of file gammatest.c.
Referenced by main().
#define MINVAL 30
Definition at line 28 of file gammatest.c.
Referenced by main().
#define MAXVAL 210
Definition at line 29 of file gammatest.c.
Referenced by main().
Function Documentation
main (int argc, char ** argv)
Definition at line 31 of file gammatest.c.
References ERROR_INT, filein, GPLOT_LINES, GPLOT_X11, gplotAddPlot(), gplotCreate(), gplotDestroy(), gplotMakeOutput(), gplotSimple1(), IFF_JFIF_JPEG, MAXVAL, MINVAL, NPLOTS, NULL, numaDestroy(), numaGammaTRC(), numaMakeSequence(), pixDestroy(), pixGammaTRC(), pixRead(), pixWrite(), startTimer(), and stopTimer().