Leptonica: prog/genfonts.c File Reference
genfonts.c File Reference
This program can be used to generate characters for a font and save them in .pixa format.
#include "allheaders.h"
Defines
#define NFONTS 9
#define TEST_DIR "/tmp/fonts"
#define INSTALL_DIR "fonts"
#define DEBUG 1
Functions
main (int argc, char **argv)
Variables
const char * outputfonts []
const l_int32 sizes [] = { 4, 6, 8, 10, 12, 14, 16, 18, 20 }
Detailed Description
This program can be used to generate characters for a font and save them in .pixa format.
Definition in file genfonts.c.
Define Documentation
#define NFONTS 9
Definition at line 32 of file genfonts.c.
#define TEST_DIR "/tmp/fonts"
Definition at line 33 of file genfonts.c.
Referenced by main().
#define INSTALL_DIR "fonts"
Definition at line 34 of file genfonts.c.
Referenced by main().
#define DEBUG 1
Definition at line 44 of file genfonts.c.
Function Documentation
main (int argc, char ** argv)
Definition at line 47 of file genfonts.c.
References buf, DIRECTORY, ERROR_INT, genPathname(), INSTALL_DIR, lept_free(), outputfonts, pixaDestroy(), pixaDisplayTiled(), pixaGenerateFont(), pixaGetCount(), pixaGetFont(), pixaRead(), pixaSaveFont(), pixaWrite(), pixDestroy(), pixDisplay(), sizes, startTimer(), stopTimer(), and TEST_DIR.
Variable Documentation
const char* outputfonts[]
Initial value:
 {"chars-4.pixa", "chars-6.pixa",
                              "chars-8.pixa", "chars-10.pixa",
                              "chars-12.pixa", "chars-14.pixa",
                              "chars-16.pixa", "chars-18.pixa",
                              "chars-20.pixa"}
Definition at line 36 of file genfonts.c.
Referenced by main().
const l_int32 sizes[] = { 4, 6, 8, 10, 12, 14, 16, 18, 20 }
Definition at line 42 of file genfonts.c.
Referenced by generateOutputDataPdf(), main(), pmsCreate(), and ptraConcatenatePdfToData().