Leptonica: src/gifiostub.c File Reference
gifiostub.c File Reference
Read/write gif format from/to file and memory.
#include "allheaders.h"
Functions
PIX * pixReadStreamGif (FILE *fp)
l_int32 pixWriteStreamGif (FILE *fp, PIX *pix)
PIX * pixReadMemGif (const l_uint8 *cdata, size_t size)
l_int32 pixWriteMemGif (l_uint8 **pdata, size_t *psize, PIX *pix)
Detailed Description
Read/write gif format from/to file and memory.
Definition in file gifiostub.c.
Function Documentation
PIX* pixReadStreamGif (FILE * fp)
Definition at line 32 of file gifiostub.c.
References ERROR_PTR, and NULL.
Referenced by pixReadStream().
l_int32 pixWriteStreamGif (FILE * fp, PIX * pix)
Definition at line 37 of file gifiostub.c.
References ERROR_INT.
Referenced by pixWriteStream().
PIX* pixReadMemGif (const l_uint8 * cdata, size_t size)
Definition at line 42 of file gifiostub.c.
References ERROR_PTR, and NULL.
Referenced by pixReadHeaderMem(), and pixReadMem().
l_int32 pixWriteMemGif (l_uint8 ** pdata, size_t * psize, PIX * pix)
Definition at line 47 of file gifiostub.c.
References ERROR_INT.
Referenced by pixWriteMem().