Leptonica: prog/graymorph1_reg.c File Reference
graymorph1_reg.c File Reference
(1) Tests the interpreter for grayscale morphology, as given in morphseq.c. (2) Tests composite operations: tophat and hdome. (3) Tests duality for grayscale erode/dilate, open/close, and black/white tophat. (4) Demonstrates closing plus white tophat. Note that this combination of operations can be quite useful. (5) Demonstrates a method of doing contrast enhancement by taking 3 * pixs and subtracting from this the closing and opening of pixs. (6) Playing around: extract the feynman diagrams from the stamp, using the tophat.
#include "allheaders.h"
Defines
#define WSIZE 7
#define HSIZE 7
#define BUF_SIZE 512
#define HORIZ_SEP 0
Functions
static void pixCompare (PIX *pix, PIX *pix2, const char *msg1, const char *msg2)
main (int argc, char **argv)
Detailed Description
(1) Tests the interpreter for grayscale morphology, as given in morphseq.c. (2) Tests composite operations: tophat and hdome. (3) Tests duality for grayscale erode/dilate, open/close, and black/white tophat. (4) Demonstrates closing plus white tophat. Note that this combination of operations can be quite useful. (5) Demonstrates a method of doing contrast enhancement by taking 3 * pixs and subtracting from this the closing and opening of pixs. (6) Playing around: extract the feynman diagrams from the stamp, using the tophat.
Definition in file graymorph1_reg.c.
Define Documentation
#define WSIZE 7
Definition at line 44 of file graymorph1_reg.c.
Referenced by main().
#define HSIZE 7
Definition at line 45 of file graymorph1_reg.c.
Referenced by main().
#define BUF_SIZE 512
Definition at line 46 of file graymorph1_reg.c.
Referenced by main().
#define HORIZ_SEP 0
Definition at line 47 of file graymorph1_reg.c.
Referenced by main().
Function Documentation
static void pixCompare (PIX * pix, PIX * pix2, const char * msg1, const char * msg2) [static]
Definition at line 291 of file graymorph1_reg.c.
References pixDisplayWrite(), and pixEqual().
Referenced by main().
main (int argc, char ** argv)
Definition at line 53 of file graymorph1_reg.c.
References BUF_SIZE, ERROR_INT, filein, HORIZ_SEP, HSIZE, IFF_PNG, L_ARITH_ADD, L_ARITH_SUBTRACT, L_LINEAR_SCALE, L_LOG_SCALE, L_TOPHAT_BLACK, L_TOPHAT_WHITE, NULL, PIX_SRC, pixaccAdd(), pixaccCreate(), pixaccDestroy(), pixaccFinal(), pixaccMultConst(), pixaccSubtract(), pixAccumulate(), pixCloseGray(), pixCompare(), pixConvertRGBToGray(), pixConvertTo32(), pixCreate(), pixDestroy(), pixDilateGray(), pixDisplayMultiple(), pixDisplayWrite(), pixErodeGray(), pixFinalAccumulate(), pixGammaTRC(), pixGetColormap(), pixGetDimensions(), pixGetHeight(), pixGetWidth(), pixGrayMorphSequence(), pixHDome(), pixInitAccumulate(), pixInvert(), pixMaxDynamicRange(), pixMultConstAccumulate(), pixOpenGray(), pixRasterop(), pixRead(), pixRemoveColormap(), pixSetAllArbitrary(), pixThresholdToBinary(), pixTophat(), pixWrite(), REMOVE_CMAP_TO_FULL_COLOR, REMOVE_CMAP_TO_GRAYSCALE, and WSIZE.