Leptonica: prog/ioformats_reg.c File Reference
ioformats_reg.c File Reference
This is the primary Leptonica regression test for lossless read/write I/O to standard image files (png, tiff, bmp, etc.)
#include "allheaders.h"
Defines
#define BMP_FILE "test1.bmp"
#define FILE_1BPP "feyn.tif"
#define FILE_2BPP "speckle2.png"
#define FILE_2BPP_C "weasel2.4g.png"
#define FILE_4BPP "speckle4.png"
#define FILE_4BPP_C "weasel4.16c.png"
#define FILE_8BPP_1 "dreyfus8.png"
#define FILE_8BPP_2 "weasel8.240c.png"
#define FILE_8BPP_3 "test8.jpg"
#define FILE_16BPP "test16.tif"
#define FILE_32BPP "marge.jpg"
Functions
static l_int32 testcomp (const char *filename, PIX *pix, l_int32 comptype)
static l_int32 testcomp_mem (PIX *pixs, PIX **ppixt, l_int32 index, l_int32 format)
static l_int32 test_writemem (PIX *pixs, l_int32 format, char *psfile)
static PIX * make_24_bpp_pix (PIX *pixs)
static l_int32 get_header_data (const char *filename, l_int32 true_format)
static void get_tiff_compression_name (char *buf, l_int32 format)
main (int argc, char **argv)
Variables
LEPT_DLL const char * ImageFileFormatExtensions []
Detailed Description
This is the primary Leptonica regression test for lossless read/write I/O to standard image files (png, tiff, bmp, etc.)
Definition in file ioformats_reg.c.
Define Documentation
#define BMP_FILE "test1.bmp"
Definition at line 57 of file ioformats_reg.c.
Referenced by main().
#define FILE_1BPP "feyn.tif"
Definition at line 58 of file ioformats_reg.c.
Referenced by main().
#define FILE_2BPP "speckle2.png"
Definition at line 59 of file ioformats_reg.c.
Referenced by main().
#define FILE_2BPP_C "weasel2.4g.png"
Definition at line 60 of file ioformats_reg.c.
Referenced by main().
#define FILE_4BPP "speckle4.png"
Definition at line 61 of file ioformats_reg.c.
Referenced by main().
#define FILE_4BPP_C "weasel4.16c.png"
Definition at line 62 of file ioformats_reg.c.
Referenced by main().
#define FILE_8BPP_1 "dreyfus8.png"
Definition at line 63 of file ioformats_reg.c.
Referenced by main().
#define FILE_8BPP_2 "weasel8.240c.png"
Definition at line 64 of file ioformats_reg.c.
Referenced by main().
#define FILE_8BPP_3 "test8.jpg"
Definition at line 65 of file ioformats_reg.c.
Referenced by main().
#define FILE_16BPP "test16.tif"
Definition at line 66 of file ioformats_reg.c.
Referenced by main().
#define FILE_32BPP "marge.jpg"
Definition at line 67 of file ioformats_reg.c.
Referenced by main().
Function Documentation
static l_int32 testcomp (const char * filename, PIX * pix, l_int32 comptype) [static]
Definition at line 464 of file ioformats_reg.c.
References FALSE, findFileFormatStream(), lept_fclose(), lept_fopen(), pixDestroy(), pixEqual(), pixRead(), and TRUE.
Referenced by main().
static l_int32 testcomp_mem (PIX * pixs, PIX ** ppixt, l_int32 index, l_int32 format) [static]
Definition at line 493 of file ioformats_reg.c.
References NULL, pixDestroy(), and pixEqual().
Referenced by main().
static l_int32 test_writemem (PIX * pixs, l_int32 format, char * psfile) [static]
Definition at line 514 of file ioformats_reg.c.
References IFF_JFIF_JPEG, IFF_PNG, IFF_PS, IFF_TIFF, l_binaryWrite(), lept_free(), NULL, pixDestroy(), pixDisplayWrite(), pixEqual(), pixReadMem(), pixWriteMem(), pixWriteMemPS(), size, and TRUE.
Referenced by main().
static PIX * make_24_bpp_pix (PIX * pixs) [static]
Definition at line 571 of file ioformats_reg.c.
References extractRGBValues(), NULL, pixCreate(), pixGetData(), pixGetDimensions(), and pixGetWpl().
Referenced by main().
static l_int32 get_header_data (const char * filename, l_int32 true_format) [static]
Definition at line 600 of file ioformats_reg.c.
References buf, get_tiff_compression_name(), IFF_JFIF_JPEG, IFF_PNG, IFF_PNM, IFF_TIFF, IFF_TIFF_G3, IFF_TIFF_G4, IFF_TIFF_LZW, IFF_TIFF_PACKBITS, IFF_TIFF_RLE, IFF_TIFF_ZIP, ImageFileFormatExtensions, l_binaryRead(), lept_free(), nbytesInFile(), pixReadHeader(), and pixReadHeaderMem().
Referenced by main().
static void get_tiff_compression_name (char * buf, l_int32 format) [static]
Definition at line 677 of file ioformats_reg.c.
References IFF_TIFF, IFF_TIFF_G3, IFF_TIFF_G4, IFF_TIFF_LZW, IFF_TIFF_PACKBITS, IFF_TIFF_RLE, and IFF_TIFF_ZIP.
Referenced by get_header_data().
main (int argc, char ** argv)
Definition at line 79 of file ioformats_reg.c.
References BMP_FILE, FALSE, FILE_16BPP, FILE_1BPP, FILE_2BPP, FILE_2BPP_C, FILE_32BPP, FILE_4BPP, FILE_4BPP_C, FILE_8BPP_1, FILE_8BPP_2, FILE_8BPP_3, genTempFilename(), get_header_data(), IFF_BMP, IFF_JFIF_JPEG, IFF_PNG, IFF_PNM, IFF_PS, IFF_TIFF, IFF_TIFF_G3, IFF_TIFF_G4, IFF_TIFF_LZW, IFF_TIFF_PACKBITS, IFF_TIFF_RLE, IFF_TIFF_ZIP, ioFormatTest(), l_binaryRead(), L_CLONE, L_INSERT, lept_free(), make_24_bpp_pix(), nbytesInFile(), NULL, pixaAddPix(), pixaCreate(), pixaDestroy(), pixaDisplayUnsplit(), pixaGetCount(), pixaGetPix(), pixaSplitPix(), pixClipToForeground(), pixConvert16To8(), pixConvert1To2(), pixConvert1To4(), pixDestroy(), pixDisplayWrite(), pixEqual(), pixGetDepth(), pixGetInputFormat(), pixRead(), pixReadMemTiff(), pixWrite(), pixWriteMemTiff(), pixWriteTiff(), readHeaderMemTiff(), regTestCleanup(), regTestCompareSimilarPix(), regTestSetup(), size, test_writemem(), testcomp(), testcomp_mem(), and TRUE.
Variable Documentation
LEPT_DLL const char* ImageFileFormatExtensions[]
Definition at line 80 of file writefile.c.