Leptonica: prog/kernel_reg.c File Reference
kernel_reg.c File Reference
Test kernel creation, convolution,.
#include <string.h>
#include <unistd.h>
#include "allheaders.h"
Functions
main (int argc, char **argv)
Variables
static const char * kdatastr = " 24.9 50 80 50 20 "
Detailed Description
Test kernel creation, convolution,.
Definition in file kernel_reg.c.
Function Documentation
main (int argc, char ** argv)
Definition at line 34 of file kernel_reg.c.
References boxCreate(), boxDestroy(), COLOR_GREEN, L_RegParams::display, FALSE, GPLOT_PNG, GPLOT_X11, IFF_JFIF_JPEG, IFF_PNG, kdatastr, kernelCreateFromFile(), kernelCreateFromPix(), kernelCreateFromString(), kernelDestroy(), kernelDisplayInPix(), kernelGetSum(), kernelRead(), kernelWrite(), l_binaryWrite(), L_COMPARE_ABS_DIFF, L_COPY, lept_free(), makeDoGKernel(), makeFlatKernel(), makeGaussianKernel(), makeGaussianKernelSep(), NULL, pixaCreate(), pixaDestroy(), pixaDisplay(), pixBlockconv(), pixBlockconvTiled(), pixClipRectangle(), pixCompareGray(), pixConvolve(), pixConvolveRGB(), pixConvolveRGBSep(), pixConvolveSep(), pixCreate(), pixDestroy(), pixDisplayWithTitle(), pixEqual(), pixRead(), pixSaveTiled(), pixScaleRGBToGrayFast(), pixScaleToGray4(), pixSetPixel(), pixWrite(), regTestCheckFile(), regTestCleanup(), regTestCompareFiles(), regTestComparePix(), regTestCompareSimilarPix(), regTestSetup(), sarrayAddString(), sarrayCreate(), sarrayDestroy(), sarrayToString(), startTimer(), stopTimer(), and TRUE.
Variable Documentation
const char* kdatastr = " 24.9 50 80 50 20 " [static]
Definition at line 28 of file kernel_reg.c.
Referenced by main().