Leptonica: src/libversions.c File Reference
libversions.c File Reference
Returns string with image library versions.
#include "allheaders.h"
#include "gif_lib.h"
#include "jpeglib.h"
#include "jerror.h"
#include "png.h"
#include "tiffio.h"
#include "zlib.h"
Defines
#define stringJoinInPlace(s1, s2) tempStrP = stringJoin(s1,s2); FREE(s1); s1 = tempStrP;
Functions
char * getImagelibVersions ()
Detailed Description
Returns string with image library versions.
     Image library version number
         char      *getImagelibVersions()
Definition in file libversions.c.
Define Documentation
#define stringJoinInPlace (s1, s2) tempStrP = stringJoin(s1,s2); FREE(s1); s1 = tempStrP;
Definition at line 56 of file libversions.c.
Referenced by getImagelibVersions().
Function Documentation
char* getImagelibVersions ()
getImagelibVersions()
Return: string of version numbers (e.g., libgif 4.1.6 libjpeg 8b libpng 1.4.3 libtiff 3.9.4 zlib 1.2.5
Notes: (1) The caller has responsibility to free the memory.
Definition at line 77 of file libversions.c.
References FREE, NULL, stringJoinInPlace, stringNew(), and strtokSafe().
Referenced by main(), and regTestSetup().