Leptonica: prog/livre_pageseg.c File Reference
livre_pageseg.c File Reference
Makes Figures 2-5 in Chapter 18, "Document Image Applications" of the book "Mathematical morphology: from theory to applications"; demonstrates page segmentation.
#include <stdio.h>
#include <stdlib.h>
#include "allheaders.h"
Defines
#define DFLAG 0
Functions
l_int32 DoPageSegmentation (PIX *pixs, l_int32 which)
main (int argc, char **argv)
Detailed Description
Makes Figures 2-5 in Chapter 18, "Document Image Applications" of the book "Mathematical morphology: from theory to applications"; demonstrates page segmentation.
Definition in file livre_pageseg.c.
Define Documentation
#define DFLAG 0
Definition at line 37 of file livre_pageseg.c.
Referenced by DoPageSegmentation().
Function Documentation
l_int32 DoPageSegmentation (PIX * pixs, l_int32 which)
Definition at line 65 of file livre_pageseg.c.
References boxaDestroy(), boxaWrite(), buf, DFLAG, ERROR_INT, IFF_PNG, L_MAX, L_SELECT_IF_BOTH, L_SELECT_IF_GTE, NULL, pixaDestroy(), pixaDisplayTiledAndScaled(), pixAnd(), pixaReadFiles(), pixCloseSafeBrick(), pixcmapResetColor(), pixConnComp(), pixDestroy(), pixDisplayWithTitle(), pixDisplayWrite(), pixDisplayWriteFormat(), pixExpandBinaryPower2(), pixGetColormap(), pixGetOuterBordersPtaa(), pixInvert(), pixMorphCompSequence(), pixMorphSequence(), pixMorphSequenceByComponent(), pixOpenBrick(), pixOr(), pixReduceRankBinaryCascade(), pixRenderRandomCmapPtaa(), pixScaleToGray2(), pixSeedfillBinary(), pixSelectBySize(), pixSubtract(), pixWrite(), pixXor(), pixZero(), PROCNAME, and ptaaDestroy().
Referenced by main().
main (int argc, char ** argv)
Definition at line 42 of file livre_pageseg.c.
References DoPageSegmentation(), ERROR_INT, filein, NULL, pixDestroy(), and pixRead().