Leptonica: prog/lowaccess_reg.c File Reference
lowaccess_reg.c File Reference
Test low-level accessors: GET_DATA_BIT(), l_getDataBit(), pixGetPixel(), etc.
#include "allheaders.h"
Functions
static l_int32 compareResults (PIX *pixs, PIX *pixt1, PIX *pixt2, l_int32 count1, l_int32 count2, const char *descr)
main (int argc, char **argv)
Detailed Description
Test low-level accessors: GET_DATA_BIT(), l_getDataBit(), pixGetPixel(), etc.
Definition in file lowaccess_reg.c.
Function Documentation
static l_int32 compareResults (PIX * pixs, PIX * pixt1, PIX * pixt2, l_int32 count1, l_int32 count2, const char * descr) [static]
Definition at line 269 of file lowaccess_reg.c.
References pixClearAll(), and pixEqual().
Referenced by main().
main (int argc, char ** argv)
Definition at line 41 of file lowaccess_reg.c.
References compareResults(), GET_DATA_BIT, GET_DATA_BYTE, GET_DATA_DIBIT, GET_DATA_FOUR_BYTES, GET_DATA_QBIT, GET_DATA_TWO_BYTES, l_getDataBit(), l_getDataByte(), l_getDataDibit(), l_getDataFourBytes(), l_getDataQbit(), l_getDataTwoBytes(), l_setDataBit(), l_setDataByte(), l_setDataDibit(), l_setDataFourBytes(), l_setDataQbit(), l_setDataTwoBytes(), lept_free(), NULL, pixCreateTemplate(), pixDestroy(), pixGetData(), pixGetDimensions(), pixGetLinePtrs(), pixGetPixel(), pixGetWpl(), pixRead(), SET_DATA_BIT, SET_DATA_BYTE, SET_DATA_DIBIT, SET_DATA_FOUR_BYTES, SET_DATA_QBIT, SET_DATA_TWO_BYTES, startTimer(), stopTimer(), HeapElement::x, and HeapElement::y.