Leptonica: prog/maze_reg.c File Reference
maze_reg.c File Reference
Tests the functions in maze.c: binary and gray maze search, largest rectangle in bg or fg.
#include <string.h>
#include "allheaders.h"
Defines
#define NPATHS 6
Functions
main (int argc, char **argv)
Variables
static const l_int32 x0 [NPATHS] = {42, 73, 73, 42, 324, 471}
static const l_int32 y0 [NPATHS] = {117, 319, 319, 117, 170, 201}
static const l_int32 x1 [NPATHS] = {419, 419, 233, 326, 418, 128}
static const l_int32 y1 [NPATHS] = {383, 383, 112, 168, 371, 341}
static const l_int32 NBOXES = 20
static const l_int32 POLARITY = 0
Detailed Description
Tests the functions in maze.c: binary and gray maze search, largest rectangle in bg or fg.
Definition in file maze_reg.c.
Define Documentation
#define NPATHS 6
Definition at line 26 of file maze_reg.c.
Referenced by main().
Function Documentation
main (int argc, char ** argv)
Definition at line 35 of file maze_reg.c.
References boxaAddBox(), boxaCreate(), boxaDestroy(), boxaGetBox(), boxDestroy(), boxGetGeometry(), L_RegParams::display, FALSE, generateBinaryMaze(), IFF_PNG, L_CLONE, L_INSERT, L_NEG_SLOPE_LINE, NBOXES, NPATHS, NULL, pixaCreate(), pixaDestroy(), pixaDisplay(), pixcmapCreateRandom(), pixcmapGetColor(), pixConvertTo8(), pixDestroy(), pixDisplayPta(), pixDisplayPtaa(), pixDisplayWithTitle(), pixExpandBinaryReplicate(), pixFindLargestRectangle(), pixGetDimensions(), pixRead(), pixRenderHashBoxArb(), pixSaveTiledOutline(), pixScaleBySampling(), pixSearchBinaryMaze(), pixSearchGrayMaze(), pixSetColormap(), pixSetInRect(), POLARITY, ptaaAddPta(), ptaaCreate(), ptaaDestroy(), ptaDestroy(), regTestCleanup(), regTestSetup(), regTestWritePixAndCheck(), x0, x1, y0, and y1.
Variable Documentation
const l_int32 x0[NPATHS] = {42, 73, 73, 42, 324, 471} [static]
Definition at line 27 of file maze_reg.c.
Referenced by kernelDisplayInPix(), main(), numaDifferentiateInterval(), numaIntegrateInterval(), numaInterpolateArbxInterval(), numaInterpolateEqxInterval(), numaLowPassIntervals(), numaThresholdEdges(), pixDisplayDiffBinary(), pixReadStreamPng(), pixSearchForRectangle(), pixSetBlackOrWhiteBoxa(), pixSetTextblock(), pixSetTextline(), pixWriteStreamBmp(), pixWriteStreamPng(), rasteropUniGeneralLow(), rasteropUniWordAlignedLow(), rasteropVipLow(), and selDisplayInPix().
const l_int32 y0[NPATHS] = {117, 319, 319, 117, 170, 201} [static]
Definition at line 28 of file maze_reg.c.
Referenced by kernelDisplayInPix(), main(), pixSearchForRectangle(), pixSetTextblock(), and selDisplayInPix().
const l_int32 x1[NPATHS] = {419, 419, 233, 326, 418, 128} [static]
Definition at line 29 of file maze_reg.c.
Referenced by main().
const l_int32 y1[NPATHS] = {383, 383, 112, 168, 371, 341} [static]
Definition at line 30 of file maze_reg.c.
Referenced by main().
const l_int32 NBOXES = 20 [static]
Definition at line 32 of file maze_reg.c.
Referenced by main().
const l_int32 POLARITY = 0 [static]
Definition at line 33 of file maze_reg.c.
Referenced by main().