Leptonica: prog/morphtest1.c File Reference
morphtest1.c File Reference
Exploration of rasterop-based morphological operations.
#include <stdio.h>
#include <stdlib.h>
#include "allheaders.h"
Defines
#define NTIMES 100
#define IMAGE_SIZE 8.
#define SEL_SIZE 9
#define BASIC_OPS 1.
#define CPU_SPEED 866.
Functions
main (int argc, char **argv)
Detailed Description
Exploration of rasterop-based morphological operations.
Definition in file morphtest1.c.
Define Documentation
#define NTIMES 100
Definition at line 27 of file morphtest1.c.
Referenced by main().
#define IMAGE_SIZE 8.
Definition at line 28 of file morphtest1.c.
Referenced by main().
#define SEL_SIZE 9
Definition at line 29 of file morphtest1.c.
Referenced by main().
#define BASIC_OPS 1.
Definition at line 30 of file morphtest1.c.
Referenced by main().
#define CPU_SPEED 866.
Definition at line 31 of file morphtest1.c.
Referenced by main().
Function Documentation
main (int argc, char ** argv)
Definition at line 35 of file morphtest1.c.
References BASIC_OPS, CPU_SPEED, ERROR_INT, filein, IFF_PNG, IMAGE_SIZE, NTIMES, NULL, pixCreateTemplate(), pixDestroy(), pixDilate(), pixOpen(), pixRead(), pixWrite(), pixXor(), SEL_SIZE, selaAddBasic(), selaFindSelByName(), selWriteStream(), startTimer(), and stopTimer().