Leptonica: prog/pagesegtest2.c File Reference
pagesegtest2.c File Reference
Demonstrates the use of binary morphology for some simple and fast document segmentation operations using: pixScaleToGray2(), pixReduceRankBinaryCascade(), pixOpenBrick(), pixCloseSafeBrick(), pixSeedfillBinary(), pixMorphCompSequence(), pixGetOuterBordersPtaa(). Probably same basic thing that pixGetRegionsBinary() does?
#include <stdio.h>
#include <stdlib.h>
#include "allheaders.h"
Defines
#define DFLAG 1
Functions
main (int argc, char **argv)
Variables
static const char * mask_sequence = "r11"
static const char * seed_sequence = "r1143 + o5.5+ x4"
static const char * dilation_sequence = "d3.3"
Detailed Description
Demonstrates the use of binary morphology for some simple and fast document segmentation operations using: pixScaleToGray2(), pixReduceRankBinaryCascade(), pixOpenBrick(), pixCloseSafeBrick(), pixSeedfillBinary(), pixMorphCompSequence(), pixGetOuterBordersPtaa(). Probably same basic thing that pixGetRegionsBinary() does?
Definition in file pagesegtest2.c.
Define Documentation
#define DFLAG 1
Definition at line 51 of file pagesegtest2.c.
Referenced by main().
Function Documentation
main (int argc, char ** argv)
Definition at line 53 of file pagesegtest2.c.
References DFLAG, dilation_sequence, ERROR_INT, filein, IFF_TIFF_G4, mask_sequence, NULL, pixClone(), pixConvertRGBToGrayFast(), pixDestroy(), pixDisplayWithTitle(), pixExpandBinaryPower2(), pixGetDepth(), pixMorphSequence(), pixRead(), pixSeedfillBinary(), pixSubtract(), pixThresholdToBinary(), pixWrite(), and seed_sequence.
Variable Documentation
const char* mask_sequence = "r11" [static]
Definition at line 44 of file pagesegtest2.c.
Referenced by main().
const char* seed_sequence = "r1143 + o5.5+ x4" [static]
Definition at line 47 of file pagesegtest2.c.
Referenced by main().
const char* dilation_sequence = "d3.3" [static]
Definition at line 49 of file pagesegtest2.c.
Referenced by main().