Leptonica: prog/paint_reg.c File Reference
paint_reg.c File Reference
Test various painting techniques: pixColorGray(), pixPaintThroughMask(), pixSetSelectCmap(), pixRenderLineArb(), pixRenderBoxArb(), pixRenderLineBlend(), and pixRenderBoxBlend().
#include <stdio.h>
#include <stdlib.h>
#include "allheaders.h"
Functions
main (int argc, char **argv)
Detailed Description
Test various painting techniques: pixColorGray(), pixPaintThroughMask(), pixSetSelectCmap(), pixRenderLineArb(), pixRenderBoxArb(), pixRenderLineBlend(), and pixRenderBoxBlend().
Definition in file paint_reg.c.
Function Documentation
main (int argc, char ** argv)
Definition at line 26 of file paint_reg.c.
References boxCreate(), boxDestroy(), composeRGBPixel(), ERROR_INT, L_PAINT_DARK, L_PAINT_LIGHT, NULL, pixClipRectangle(), pixcmapGetIndex(), pixColorGray(), pixColorGrayCmap(), pixConvert8To32(), pixDestroy(), pixDisplayMultiple(), pixDisplayWrite(), pixGetColormap(), pixInvert(), pixPaintThroughMask(), pixPrintStreamInfo(), pixRead(), pixRenderBoxArb(), pixRenderBoxBlend(), pixRenderLineArb(), pixRenderLineBlend(), pixSetSelectCmap(), pixThresholdTo4bpp(), pixThresholdToBinary(), Box::x, and Box::y.