Leptonica: prog/pdfiotest.c File Reference
pdfiotest.c File Reference
Tests PDF file I/O.
#include <string.h>
#include "allheaders.h"
Functions
static void GetImageMask (PIX *pixs, l_int32 res, BOXA **pboxa, const char *debugfile)
static PIX * QuantizeNonImageRegion (PIX *pixs, PIX *pixm, l_int32 levels)
main (int argc, char **argv)
Detailed Description
Tests PDF file I/O.
Definition in file pdfiotest.c.
Function Documentation
static void GetImageMask (PIX * pixs, l_int32 res, BOXA ** pboxa, const char * debugfile) [static]
Definition at line 398 of file pdfiotest.c.
References IFF_JFIF_JPEG, L_COPY, L_INSERT, NULL, pixaAddPix(), pixaCreate(), pixaDestroy(), pixaDisplayTiledInRows(), pixConnComp(), pixConvertTo1(), pixDestroy(), pixDisplay(), pixGenHalftoneMask(), pixMorphSequence(), pixSetResolution(), and pixWrite().
Referenced by main().
static PIX * QuantizeNonImageRegion (PIX * pixs, PIX * pixm, l_int32 levels) [static]
Definition at line 432 of file pdfiotest.c.
References pixCombineMasked(), pixConvertTo32(), pixConvertTo8(), pixDestroy(), and pixThresholdOn8bpp().
Referenced by main().
main (int argc, char ** argv)
Definition at line 31 of file pdfiotest.c.
References boxaDestroy(), boxaTransform(), boxCreate(), boxDestroy(), concatenatePdf(), convertFilesToPdf(), convertToPdf(), convertToPdfDataSegmented(), convertToPdfSegmented(), ERROR_INT, filesAreIdentical(), genPathname(), GetImageMask(), IFF_JFIF_JPEG, IFF_PNG, IFF_TIFF_G4, l_binaryWrite(), l_byteaDestroy(), l_byteaGetData(), l_byteaInitFromFile(), L_FIRST_IMAGE, L_FLATE_ENCODE, L_G4_ENCODE, L_JPEG_ENCODE, L_LAST_IMAGE, L_NEXT_IMAGE, l_pdfSetDateAndVersion(), l_pdfSetG4ImageMask(), lept_cp(), lept_free(), lept_mkdir(), lept_mv(), NULL, pixClipRectangle(), pixConnComp(), pixConvertTo8(), pixConvertToPdf(), pixDestroy(), pixGenHalftoneMask(), pixGetDimensions(), pixMorphSequence(), pixRead(), pixScale(), pixScaleToGray2(), pixScaleToGray3(), pixSetResolution(), pixThresholdTo4bpp(), pixWrite(), QuantizeNonImageRegion(), startTimer(), and stopTimer().