Leptonica: prog/pdfseg_reg.c File Reference
pdfseg_reg.c File Reference
Generates segmented images and encodes them efficiently in a mixed-raster pdf.
#include "allheaders.h"
Functions
main (int argc, char **argv)
Variables
static const l_int32 WIDTH = 800
Detailed Description
Generates segmented images and encodes them efficiently in a mixed-raster pdf.
Definition in file pdfseg_reg.c.
Function Documentation
main (int argc, char ** argv)
Definition at line 32 of file pdfseg_reg.c.
References boxaaAddBoxa(), boxaaCreate(), boxaAddBox(), boxaaDestroy(), boxaaWrite(), boxaCreate(), boxaDestroy(), boxaTransform(), boxCreate(), convertSegmentedFilesToPdf(), FALSE, IFF_JFIF_JPEG, L_G4_ENCODE, L_INSERT, l_pdfSetDateAndVersion(), lept_mkdir(), lept_rmdir(), NULL, pixBackgroundNormSimple(), pixConnComp(), pixConvertTo1(), pixDestroy(), pixExpandBinaryPower2(), pixGenHalftoneMask(), pixGetHeight(), pixGetWidth(), pixMaskConnComp(), pixMorphSequence(), pixRead(), pixReduceBinary2(), pixScaleToGray(), pixScaleToSize(), pixWrite(), regTestCheckFile(), regTestCleanup(), regTestSetup(), and WIDTH.
Variable Documentation
const l_int32 WIDTH = 800 [static]
Definition at line 30 of file pdfseg_reg.c.
Referenced by main().