Leptonica: prog/pixalloc_reg.c File Reference
pixalloc_reg.c File Reference
Tests custom pix allocator.
#include <math.h>
#include "allheaders.h"
Functions
PIXA * GenerateSetOfMargePix (void)
void CopyStoreClean (PIXA *pixas, l_int32 nlevels, l_int32 ncopies)
main (int argc, char **argv)
Variables
static const l_int32 logging = FALSE
static const l_int32 ncopies = 2
static const l_int32 nlevels = 4
static const l_int32 ntimes = 30
Detailed Description
Tests custom pix allocator.
Definition in file pixalloc_reg.c.
Function Documentation
PIXA * GenerateSetOfMargePix (void)
Definition at line 142 of file pixalloc_reg.c.
References boxCreate(), boxDestroy(), L_INSERT, NULL, pixaAddPix(), pixaCreate(), pixClipRectangle(), pixDestroy(), pixRead(), and pixScale().
Referenced by main().
void CopyStoreClean (PIXA * pixas, l_int32 nlevels, l_int32 ncopies)
Definition at line 168 of file pixalloc_reg.c.
References L_CLONE, L_INSERT, ncopies, nlevels, NULL, pixaaAddPixa(), pixaaCreate(), pixaAddPix(), pixaaDestroy(), pixaCreate(), pixaGetPix(), pixCopy(), and pixDestroy().
Referenced by main().
main (int argc, char ** argv)
Definition at line 49 of file pixalloc_reg.c.
References boxaDestroy(), CopyStoreClean(), GenerateSetOfMargePix(), logging, ncopies, nlevels, ntimes, NULL, numaAddNumber(), numaCreate(), numaDestroy(), pixaDestroy(), pixConnComp(), pixDestroy(), pixRead(), pmsCreate(), pmsCustomAlloc(), pmsCustomDealloc(), pmsDestroy(), setPixMemoryManager(), startTimer(), and stopTimer().
Variable Documentation
const l_int32 logging = FALSE [static]
Definition at line 38 of file pixalloc_reg.c.
Referenced by main().
const l_int32 ncopies = 2 [static]
Definition at line 40 of file pixalloc_reg.c.
Referenced by CopyStoreClean(), and main().
const l_int32 nlevels = 4 [static]
Definition at line 41 of file pixalloc_reg.c.
Referenced by boxaaQuadtreeRegions(), CopyStoreClean(), fpixaDisplayQuadtree(), main(), makeGrayQuantIndexTable(), makeGrayQuantTargetTable(), pixcmapCreateLinear(), pixQuadtreeMean(), pixQuadtreeVariance(), and pmsCreate().
const l_int32 ntimes = 30 [static]
Definition at line 42 of file pixalloc_reg.c.
Referenced by main().