Leptonica: prog/pixserial_reg.c File Reference
pixserial_reg.c File Reference
Tests the fast (uncompressed) serialization of pix to a string in memory and the deserialization back to a pix.
#include "allheaders.h"
Functions
main (int argc, char **argv)
Variables
static l_int32 nfiles = 10
static const char * filename []
Detailed Description
Tests the fast (uncompressed) serialization of pix to a string in memory and the deserialization back to a pix.
Definition in file pixserial_reg.c.
Function Documentation
main (int argc, char ** argv)
Definition at line 40 of file pixserial_reg.c.
References boxCreate(), boxDestroy(), buf, filename, L_RegParams::fp, IFF_SPIX, L_RegParams::index, l_binaryRead(), l_binaryWrite(), L_MIN, lept_free(), nfiles, NULL, pixClipRectangle(), pixDeserializeFromMemory(), pixDestroy(), pixGetDimensions(), pixRead(), pixReadHeader(), pixReadHeaderMem(), pixSerializeToMemory(), pixWrite(), pixWriteMem(), regTestCheckFile(), regTestCleanup(), regTestComparePix(), regTestSetup(), size, startTimer(), and stopTimer().
Variable Documentation
l_int32 nfiles = 10 [static]
Definition at line 26 of file pixserial_reg.c.
Referenced by convertFilesTo1bpp(), getNumberedPathnamesInDirectory(), getSortedPathnamesInDirectory(), jbAddPages(), jbCorrelation(), jbRankHaus(), jbWordsInTextlines(), lept_rmdir(), main(), pixHtmlViewer(), sarrayConvertFilesFittedToPS(), sarrayConvertFilesToPS(), and writeMultipageTiffSA().
const char* filename[] [static]
Initial value:
 {
                         "feyn.tif",
                         "dreyfus2.png",
                         "dreyfus4.png",
                         "weasel4.16c.png",
                         "dreyfus8.png",
                         "weasel8.240c.png",
                         "karen8.jpg",
                         "test16.tif",
                         "marge.jpg",
                         "test24.jpg"
                            }
Definition at line 27 of file pixserial_reg.c.
Referenced by jbCorrelation(), jbRankHaus(), main(), and pixWriteTempfile().