Leptonica: prog/plottest.c File Reference
plottest.c File Reference
Regression test of the gplot library functions that generate the plot commands and data required for input to gnuplot.
#include <string.h>
#include <math.h>
#include "allheaders.h"
Defines
#define GPLOT_STYLE GPLOT_LINES
#define GPLOT_OUTPUT GPLOT_X11
Functions
main (int argc, char **argv)
Detailed Description
Regression test of the gplot library functions that generate the plot commands and data required for input to gnuplot.
Definition in file plottest.c.
Define Documentation
#define GPLOT_STYLE GPLOT_LINES
Definition at line 37 of file plottest.c.
#define GPLOT_OUTPUT GPLOT_X11
Definition at line 46 of file plottest.c.
Function Documentation
main (int argc, char ** argv)
Definition at line 49 of file plottest.c.
References ERROR_INT, GPLOT_PNG, GPLOT_X11, gplotAddPlot(), gplotCreate(), gplotDestroy(), gplotMakeOutput(), gplotRead(), gplotWrite(), l_binaryRead(), lept_free(), NULL, numaAddNumber(), numaCreate(), numaDestroy(), GPlot::outformat, GPlot::outname, stringReplace(), GPlot::title, HeapElement::x, y1, and y2.