Leptonica: prog/projective_reg.c File Reference
projective_reg.c File Reference
Test projective image transformations using pixProjectiveSampledPta() and pixProjectivePta().
#include <stdio.h>
#include <stdlib.h>
#include "allheaders.h"
Defines
#define ADDED_BORDER_PIXELS 500
#define ALL 1
Functions
static void MakePtas (l_int32 i, PTA **pptas, PTA **pptad)
main (int argc, char **argv)
Variables
static const l_int32 x1 [] = { 300, 300, 300, 300, 32}
static const l_int32 y1 [] = {1200, 1200, 1250, 1250, 934}
static const l_int32 x2 [] = {1200, 1200, 1125, 1300, 487}
static const l_int32 y2 [] = {1100, 1100, 1100, 1250, 934}
static const l_int32 x3 [] = { 200, 200, 200, 250, 32}
static const l_int32 y3 [] = { 200, 200, 200, 300, 67}
static const l_int32 x4 [] = {1200, 1200, 1300, 1250, 332}
static const l_int32 y4 [] = { 400, 200, 200, 300, 57}
static const l_int32 xp1 [] = { 300, 300, 1150, 300, 32}
static const l_int32 yp1 [] = {1200, 1400, 1150, 1350, 934}
static const l_int32 xp2 [] = {1100, 1400, 320, 1300, 487}
static const l_int32 yp2 [] = {1000, 1500, 1300, 1200, 904}
static const l_int32 xp3 [] = { 250, 200, 1310, 300, 61}
static const l_int32 yp3 [] = { 200, 300, 250, 325, 83}
static const l_int32 xp4 [] = {1250, 1200, 240, 1250, 412}
static const l_int32 yp4 [] = { 300, 300, 250, 350, 83}
Detailed Description
Test projective image transformations using pixProjectiveSampledPta() and pixProjectivePta().
Definition in file projective_reg.c.
Define Documentation
#define ADDED_BORDER_PIXELS 500
Definition at line 50 of file projective_reg.c.
Referenced by main().
#define ALL 1
Definition at line 51 of file projective_reg.c.
Function Documentation
static void MakePtas (l_int32 i, PTA ** pptas, PTA ** pptad) [static]
Definition at line 230 of file projective_reg.c.
References ptaAddPt(), ptaCreate(), x1, x2, x3, x4, xp1, xp2, xp3, xp4, y1, y2, y3, y4, yp1, yp2, yp3, and yp4.
Referenced by main().
main (int argc, char ** argv)
Definition at line 54 of file projective_reg.c.
References ADDED_BORDER_PIXELS, ERROR_INT, IFF_PNG, L_BRING_IN_WHITE, MakePtas(), NULL, pixaCreate(), pixAddBorder(), pixaDestroy(), pixaDisplay(), pixDestroy(), pixDisplay(), pixProjectivePta(), pixProjectiveSampledPta(), pixRead(), pixRemoveBorder(), pixSaveTiled(), pixScale(), pixScaleToGray3(), pixWrite(), pixXor(), ptaDestroy(), startTimer(), stopTimer(), HeapElement::x, and HeapElement::y.
Variable Documentation
const l_int32 x1[] = { 300, 300, 300, 300, 32} [static]
Definition at line 32 of file projective_reg.c.
Referenced by MakePtas().
const l_int32 y1[] = {1200, 1200, 1250, 1250, 934} [static]
Definition at line 33 of file projective_reg.c.
Referenced by MakePtas().
const l_int32 x2[] = {1200, 1200, 1125, 1300, 487} [static]
Definition at line 34 of file projective_reg.c.
Referenced by MakePtas().
const l_int32 y2[] = {1100, 1100, 1100, 1250, 934} [static]
Definition at line 35 of file projective_reg.c.
Referenced by MakePtas().
const l_int32 x3[] = { 200, 200, 200, 250, 32} [static]
Definition at line 36 of file projective_reg.c.
Referenced by MakePtas().
const l_int32 y3[] = { 200, 200, 200, 300, 67} [static]
Definition at line 37 of file projective_reg.c.
Referenced by MakePtas().
const l_int32 x4[] = {1200, 1200, 1300, 1250, 332} [static]
Definition at line 38 of file projective_reg.c.
Referenced by MakePtas().
const l_int32 y4[] = { 400, 200, 200, 300, 57} [static]
Definition at line 39 of file projective_reg.c.
Referenced by MakePtas().
const l_int32 xp1[] = { 300, 300, 1150, 300, 32} [static]
Definition at line 41 of file projective_reg.c.
Referenced by MakePtas().
const l_int32 yp1[] = {1200, 1400, 1150, 1350, 934} [static]
Definition at line 42 of file projective_reg.c.
Referenced by MakePtas().
const l_int32 xp2[] = {1100, 1400, 320, 1300, 487} [static]
Definition at line 43 of file projective_reg.c.
Referenced by MakePtas().
const l_int32 yp2[] = {1000, 1500, 1300, 1200, 904} [static]
Definition at line 44 of file projective_reg.c.
Referenced by MakePtas().
const l_int32 xp3[] = { 250, 200, 1310, 300, 61} [static]
Definition at line 45 of file projective_reg.c.
Referenced by MakePtas().
const l_int32 yp3[] = { 200, 300, 250, 325, 83} [static]
Definition at line 46 of file projective_reg.c.
Referenced by MakePtas().
const l_int32 xp4[] = {1250, 1200, 240, 1250, 412} [static]
Definition at line 47 of file projective_reg.c.
Referenced by MakePtas().
const l_int32 yp4[] = { 300, 300, 250, 350, 83} [static]
Definition at line 48 of file projective_reg.c.
Referenced by MakePtas().