Leptonica: prog/psioseg_reg.c File Reference
psioseg_reg.c File Reference
This tests the PostScript output for images with mixed text and images, coming from source of different depths, with and without colormaps. Illustrates binary halftone segmentation, combining images with masks, PS generation.
#include "allheaders.h"
Functions
main (int argc, char **argv)
Detailed Description
This tests the PostScript output for images with mixed text and images, coming from source of different depths, with and without colormaps. Illustrates binary halftone segmentation, combining images with masks, PS generation.
Definition in file psioseg_reg.c.
Function Documentation
main (int argc, char ** argv)
Definition at line 38 of file psioseg_reg.c.
References buf, convertSegmentedPagesToPS(), genPathname(), IFF_JFIF_JPEG, IFF_PNG, IFF_TIFF_G4, lept_free(), lept_mkdir(), NULL, PIX_SRC, pixCombineMasked(), pixConvertRGBToLuminance(), pixConvertTo32(), pixCreate(), pixDestroy(), pixGetDimensions(), pixGetRegionsBinary(), pixOctreeColorQuant(), pixOctreeQuantNumColors(), pixRasterop(), pixRead(), pixScale(), pixSetAll(), pixSubtract(), pixWrite(), regTestCheckFile(), regTestCleanup(), regTestSetup(), and regTestWritePixAndCheck().