Leptonica: src/rotateshear.c File Reference
rotateshear.c File Reference
Image rotation by shear.
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <math.h>
#include "allheaders.h"
Functions
PIX * pixRotateShear (PIX *pixs, l_int32 xcen, l_int32 ycen, l_float32 angle, l_int32 incolor)
PIX * pixRotate2Shear (PIX *pixs, l_int32 xcen, l_int32 ycen, l_float32 angle, l_int32 incolor)
PIX * pixRotate3Shear (PIX *pixs, l_int32 xcen, l_int32 ycen, l_float32 angle, l_int32 incolor)
l_int32 pixRotateShearIP (PIX *pixs, l_int32 xcen, l_int32 ycen, l_float32 angle, l_int32 incolor)
PIX * pixRotateShearCenter (PIX *pixs, l_float32 angle, l_int32 incolor)
l_int32 pixRotateShearCenterIP (PIX *pixs, l_float32 angle, l_int32 incolor)
Variables
static const l_float32 VERY_SMALL_ANGLE = 0.001
static const l_float32 MAX_2_SHEAR_ANGLE = 0.05
Detailed Description
Image rotation by shear.
Definition in file rotateshear.c.
Function Documentation
PIX* pixRotateShear (PIX * pixs, l_int32 xcen, l_int32 ycen, l_float32 angle, l_int32 incolor)
pixRotateShear()
Input: pixs xcen (x value for which there is no horizontal shear) ycen (y value for which there is no vertical shear) angle (radians) incolor (L_BRING_IN_WHITE, L_BRING_IN_BLACK); Return: pixd, or null on error.
Notes: (1) This rotates an image about the given point, using either 2 or 3 shears. (2) A positive angle gives a clockwise rotation. (3) This brings in 'incolor' pixels from outside the image.
Definition at line 170 of file rotateshear.c.
References ERROR_PTR, L_ABS, L_BRING_IN_BLACK, L_BRING_IN_WHITE, MAX_2_SHEAR_ANGLE, NULL, pixClone(), pixRotate2Shear(), pixRotate3Shear(), PROCNAME, and VERY_SMALL_ANGLE.
Referenced by main(), and pixRotateShearCenter().
PIX* pixRotate2Shear (PIX * pixs, l_int32 xcen, l_int32 ycen, l_float32 angle, l_int32 incolor)
pixRotate2Shear()
Input: pixs xcen, ycen (center of rotation) angle (radians) incolor (L_BRING_IN_WHITE, L_BRING_IN_BLACK); Return: pixd, or null on error.
Notes: (1) This rotates the image about the given point, using the 2-shear method. It should only be used for angles smaller than MAX_2_SHEAR_ANGLE. (2) A positive angle gives a clockwise rotation. (3) 2-shear rotation by a specified angle is equivalent to the sequential transformations x' = x + tan(angle) * (y - ycen) for x-shear y' = y + tan(angle) * (x - xcen) for y-shear (4) Computation of tan(angle) is performed within the shear operation. (5) This brings in 'incolor' pixels from outside the image.
Definition at line 216 of file rotateshear.c.
References ERROR_PTR, L_ABS, L_BRING_IN_BLACK, L_BRING_IN_WHITE, NULL, pixClone(), pixDestroy(), pixHShear(), pixVShear(), PROCNAME, and VERY_SMALL_ANGLE.
Referenced by pixRotateShear().
PIX* pixRotate3Shear (PIX * pixs, l_int32 xcen, l_int32 ycen, l_float32 angle, l_int32 incolor)
pixRotate3Shear()
Input: pixs xcen, ycen (center of rotation) angle (radians) incolor (L_BRING_IN_WHITE, L_BRING_IN_BLACK); Return: pixd, or null on error.
Notes: (1) This rotates the image about the image center, using the 3-shear method. It can be used for any angle, and should be used for angles larger than MAX_2_SHEAR_ANGLE. (2) A positive angle gives a clockwise rotation. (3) 3-shear rotation by a specified angle is equivalent to the sequential transformations y' = y + tan(angle/2) * (x - xcen) for first y-shear x' = x + sin(angle) * (y - ycen) for x-shear y' = y + tan(angle/2) * (x - xcen) for second y-shear (4) Computation of tan(angle) is performed in the shear operations. (5) This brings in 'incolor' pixels from outside the image. (6) The algorithm was published by Alan Paeth: "A Fast Algorithm for General Raster Rotation," Graphics Interface '86, pp. 77-81, May 1986. A description of the method, along with an implementation, can be found in Graphics Gems, p. 179, edited by Andrew Glassner, published by Academic Press, 1990.
Definition at line 272 of file rotateshear.c.
References ERROR_PTR, L_ABS, L_BRING_IN_BLACK, L_BRING_IN_WHITE, NULL, pixClone(), pixDestroy(), pixHShear(), pixVShear(), PROCNAME, and VERY_SMALL_ANGLE.
Referenced by main(), and pixRotateShear().
l_int32 pixRotateShearIP (PIX * pixs, l_int32 xcen, l_int32 ycen, l_float32 angle, l_int32 incolor)
pixRotateShearIP()
Input: pixs (any depth; not colormapped) xcen, ycen (center of rotation) angle (radians) incolor (L_BRING_IN_WHITE, L_BRING_IN_BLACK) Return: 0 if OK; 1 on error
Notes: (1) This does an in-place rotation of the image about the image center, using the 3-shear method. (2) A positive angle gives a clockwise rotation. (3) 3-shear rotation by a specified angle is equivalent to the sequential transformations y' = y + tan(angle/2) * (x - xcen) for first y-shear x' = x + sin(angle) * (y - ycen) for x-shear y' = y + tan(angle/2) * (x - xcen) for second y-shear (4) Computation of tan(angle) is performed in the shear operations. (5) This brings in 'incolor' pixels from outside the image. (6) The pix cannot be colormapped, because the in-place operation only blits in 0 or 1 bits, not an arbitrary colormap index.
Definition at line 330 of file rotateshear.c.
References ERROR_INT, L_BRING_IN_BLACK, L_BRING_IN_WHITE, NULL, pixGetColormap(), pixHShearIP(), pixVShearIP(), and PROCNAME.
Referenced by main(), and pixRotateShearCenterIP().
PIX* pixRotateShearCenter (PIX * pixs, l_float32 angle, l_int32 incolor)
pixRotateShearCenter()
Input: pixs angle (radians) incolor (L_BRING_IN_WHITE, L_BRING_IN_BLACK) Return: pixd, or null on error
Definition at line 371 of file rotateshear.c.
References ERROR_PTR, NULL, pixGetHeight(), pixGetWidth(), pixRotateShear(), and PROCNAME.
Referenced by main(), and pixRotate().
l_int32 pixRotateShearCenterIP (PIX * pixs, l_float32 angle, l_int32 incolor)
pixRotateShearCenterIP()
Input: pixs angle (radians) incolor (L_BRING_IN_WHITE, L_BRING_IN_BLACK) Return: 0 if OK, 1 on error
Definition at line 394 of file rotateshear.c.
References ERROR_INT, pixGetHeight(), pixGetWidth(), pixRotateShearIP(), and PROCNAME.
Variable Documentation
const l_float32 VERY_SMALL_ANGLE = 0.001 [static]
Definition at line 146 of file rotateshear.c.
Referenced by pixRotate2Shear(), pixRotate3Shear(), and pixRotateShear().
const l_float32 MAX_2_SHEAR_ANGLE = 0.05 [static]
Definition at line 147 of file rotateshear.c.
Referenced by pixRotateShear().