Leptonica: prog/rotate2_reg.c File Reference
rotate2_reg.c File Reference
Regression test for rotation by shear, sampling and area mapping. Displays results from all the various types of rotations.
#include "allheaders.h"
Defines
#define BINARY_IMAGE "test1.png"
#define TWO_BPP_IMAGE "weasel2.4c.png"
#define FOUR_BPP_IMAGE1 "weasel4.11c.png"
#define FOUR_BPP_IMAGE2 "weasel4.16g.png"
#define EIGHT_BPP_IMAGE "test8.jpg"
#define EIGHT_BPP_CMAP_IMAGE1 "dreyfus8.png"
#define EIGHT_BPP_CMAP_IMAGE2 "test24.jpg"
#define RGB_IMAGE "marge.jpg"
Functions
void RotateTest (PIX *pixs, l_int32 reduction, L_REGPARAMS *rp)
main (int argc, char **argv)
Variables
static const l_float32 ANGLE1 = 3.14159265 / 30.
static const l_float32 ANGLE2 = 3.14159265 / 7.
Detailed Description
Regression test for rotation by shear, sampling and area mapping. Displays results from all the various types of rotations.
Definition in file rotate2_reg.c.
Define Documentation
#define BINARY_IMAGE "test1.png"
Definition at line 25 of file rotate2_reg.c.
Referenced by main().
#define TWO_BPP_IMAGE "weasel2.4c.png"
Definition at line 26 of file rotate2_reg.c.
Referenced by main().
#define FOUR_BPP_IMAGE1 "weasel4.11c.png"
Definition at line 27 of file rotate2_reg.c.
Referenced by main().
#define FOUR_BPP_IMAGE2 "weasel4.16g.png"
Definition at line 28 of file rotate2_reg.c.
Referenced by main().
#define EIGHT_BPP_IMAGE "test8.jpg"
Definition at line 29 of file rotate2_reg.c.
Referenced by main().
#define EIGHT_BPP_CMAP_IMAGE1 "dreyfus8.png"
Definition at line 30 of file rotate2_reg.c.
Referenced by main().
#define EIGHT_BPP_CMAP_IMAGE2 "test24.jpg"
Definition at line 31 of file rotate2_reg.c.
Referenced by main().
#define RGB_IMAGE "marge.jpg"
Definition at line 32 of file rotate2_reg.c.
Referenced by main().
Function Documentation
void RotateTest (PIX * pixs, l_int32 reduction, L_REGPARAMS * rp)
Definition at line 97 of file rotate2_reg.c.
References ANGLE1, ANGLE2, L_RegParams::display, IFF_JFIF_JPEG, IFF_PNG, L_BRING_IN_BLACK, L_BRING_IN_WHITE, L_ROTATE_AREA_MAP, L_ROTATE_SAMPLING, L_ROTATE_SHEAR, NULL, pixaCreate(), pixaDestroy(), pixaDisplay(), pixClone(), pixDestroy(), pixDisplayWithTitle(), pixGetDepth(), pixGetDimensions(), pixRotate(), pixSaveTiled(), pixScaleToGray2(), and regTestWritePixAndCheck().
Referenced by main().
main (int argc, char ** argv)
Definition at line 40 of file rotate2_reg.c.
References BINARY_IMAGE, EIGHT_BPP_CMAP_IMAGE1, EIGHT_BPP_CMAP_IMAGE2, EIGHT_BPP_IMAGE, FOUR_BPP_IMAGE1, FOUR_BPP_IMAGE2, pixDestroy(), pixOctreeColorQuant(), pixRead(), regTestCleanup(), regTestSetup(), RGB_IMAGE, RotateTest(), and TWO_BPP_IMAGE.
Variable Documentation
const l_float32 ANGLE1 = 3.14159265 / 30. [static]
Definition at line 34 of file rotate2_reg.c.
Referenced by RotateTest().
const l_float32 ANGLE2 = 3.14159265 / 7. [static]
Definition at line 35 of file rotate2_reg.c.
Referenced by RotateTest().