Leptonica: prog/rotateorth_reg.c File Reference
rotateorth_reg.c File Reference
Regression test for all rotateorth functions.
#include "allheaders.h"
Defines
#define BINARY_IMAGE "test1.png"
#define GRAYSCALE_IMAGE "test8.jpg"
#define FOUR_BPP_IMAGE "weasel4.8g.png"
#define COLORMAP_IMAGE "dreyfus8.png"
#define RGB_IMAGE "marge.jpg"
Functions
void RotateOrthTest (PIX *pix, L_REGPARAMS *rp)
main (int argc, char **argv)
Detailed Description
Regression test for all rotateorth functions.
Definition in file rotateorth_reg.c.
Define Documentation
#define BINARY_IMAGE "test1.png"
Definition at line 24 of file rotateorth_reg.c.
Referenced by main().
#define GRAYSCALE_IMAGE "test8.jpg"
Definition at line 25 of file rotateorth_reg.c.
Referenced by main().
#define FOUR_BPP_IMAGE "weasel4.8g.png"
Definition at line 26 of file rotateorth_reg.c.
Referenced by main().
#define COLORMAP_IMAGE "dreyfus8.png"
Definition at line 27 of file rotateorth_reg.c.
Referenced by main().
#define RGB_IMAGE "marge.jpg"
Definition at line 28 of file rotateorth_reg.c.
Referenced by main().
Function Documentation
void RotateOrthTest (PIX * pix, L_REGPARAMS * rp)
Definition at line 69 of file rotateorth_reg.c.
References NULL, pixCountPixels(), pixDestroy(), pixFlipLR(), pixFlipTB(), pixGetColormap(), pixRotate180(), pixRotate90(), pixXor(), pixZero(), and regTestComparePix().
Referenced by main().
main (int argc, char ** argv)
Definition at line 33 of file rotateorth_reg.c.
References BINARY_IMAGE, COLORMAP_IMAGE, FOUR_BPP_IMAGE, GRAYSCALE_IMAGE, pixDestroy(), pixRead(), regTestCleanup(), regTestSetup(), RGB_IMAGE, and RotateOrthTest().