Leptonica: src/rotateam.c File Reference
rotateam.c File Reference
Interpolated image rotation.
#include <stdio.h>
#include <string.h>
#include "allheaders.h"
Functions
PIX * pixRotateAM (PIX *pixs, l_float32 angle, l_int32 incolor)
PIX * pixRotateAMColor (PIX *pixs, l_float32 angle, l_uint32 colorval)
PIX * pixRotateAMGray (PIX *pixs, l_float32 angle, l_uint8 grayval)
PIX * pixRotateAMCorner (PIX *pixs, l_float32 angle, l_int32 incolor)
PIX * pixRotateAMColorCorner (PIX *pixs, l_float32 angle, l_uint32 fillval)
PIX * pixRotateAMGrayCorner (PIX *pixs, l_float32 angle, l_uint8 grayval)
PIX * pixRotateAMColorFast (PIX *pixs, l_float32 angle, l_uint32 colorval)
Variables
static const l_float32 VERY_SMALL_ANGLE = 0.001
Detailed Description
Interpolated image rotation.
Definition in file rotateam.c.
Function Documentation
PIX* pixRotateAM (PIX * pixs, l_float32 angle, l_int32 incolor)
pixRotateAM()
Input: pixs (2, 4, 8 bpp gray or colormapped, or 32 bpp RGB) angle (radians; clockwise is positive) incolor (L_BRING_IN_WHITE, L_BRING_IN_BLACK) Return: pixd, or null on error
Notes: (1) Rotates about image center. (2) A positive angle gives a clockwise rotation. (3) Brings in either black or white pixels from the boundary.
Definition at line 110 of file rotateam.c.
References ERROR_PTR, FALSE, L_ABS, L_BRING_IN_WHITE, NULL, pixClone(), pixConvertTo8(), pixDestroy(), pixGetDepth(), pixRemoveColormap(), pixRotateAMColor(), pixRotateAMGray(), PROCNAME, REMOVE_CMAP_BASED_ON_SRC, and VERY_SMALL_ANGLE.
Referenced by main(), and pixRotateBinaryNice().
PIX* pixRotateAMColor (PIX * pixs, l_float32 angle, l_uint32 colorval)
pixRotateAMColor()
Input: pixs (32 bpp) angle (radians; clockwise is positive) colorval (e.g., 0 to bring in BLACK, 0xffffff00 for WHITE) Return: pixd, or null on error
Notes: (1) Rotates about image center. (2) A positive angle gives a clockwise rotation. (3) Specify the color to be brought in from outside the image.
Definition at line 171 of file rotateam.c.
References ERROR_PTR, L_ABS, NULL, pixClone(), pixCreateTemplate(), pixGetData(), pixGetDepth(), pixGetDimensions(), pixGetWpl(), PROCNAME, rotateAMColorLow(), and VERY_SMALL_ANGLE.
Referenced by main(), pixRotate(), and pixRotateAM().
PIX* pixRotateAMGray (PIX * pixs, l_float32 angle, l_uint8 grayval)
pixRotateAMGray()
Input: pixs (8 bpp) angle (radians; clockwise is positive) grayval (0 to bring in BLACK, 255 for WHITE) Return: pixd, or null on error
Notes: (1) Rotates about image center. (2) A positive angle gives a clockwise rotation. (3) Specify the grayvalue to be brought in from outside the image.
Definition at line 216 of file rotateam.c.
References ERROR_PTR, L_ABS, NULL, pixClone(), pixCreateTemplate(), pixGetData(), pixGetDepth(), pixGetDimensions(), pixGetWpl(), PROCNAME, rotateAMGrayLow(), and VERY_SMALL_ANGLE.
Referenced by main(), pixRotate(), and pixRotateAM().
PIX* pixRotateAMCorner (PIX * pixs, l_float32 angle, l_int32 incolor)
pixRotateAMCorner()
Input: pixs (1, 2, 4, 8 bpp gray or colormapped, or 32 bpp RGB) angle (radians; clockwise is positive) incolor (L_BRING_IN_WHITE, L_BRING_IN_BLACK) Return: pixd, or null on error
Notes: (1) Rotates about the UL corner of the image. (2) A positive angle gives a clockwise rotation. (3) Brings in either black or white pixels from the boundary.
Definition at line 264 of file rotateam.c.
References ERROR_PTR, FALSE, L_ABS, L_BRING_IN_WHITE, NULL, pixClone(), pixConvertTo8(), pixDestroy(), pixGetDepth(), pixRemoveColormap(), pixRotateAMColorCorner(), pixRotateAMGrayCorner(), PROCNAME, REMOVE_CMAP_BASED_ON_SRC, and VERY_SMALL_ANGLE.
Referenced by main(), and RotateTest().
PIX* pixRotateAMColorCorner (PIX * pixs, l_float32 angle, l_uint32 fillval)
pixRotateAMColorCorner()
Input: pixs angle (radians; clockwise is positive) colorval (e.g., 0 to bring in BLACK, 0xffffff00 for WHITE) Return: pixd, or null on error
Notes: (1) Rotates the image about the UL corner. (2) A positive angle gives a clockwise rotation. (3) Specify the color to be brought in from outside the image.
Definition at line 323 of file rotateam.c.
References ERROR_PTR, L_ABS, NULL, pixClone(), pixCreateTemplate(), pixGetData(), pixGetDepth(), pixGetDimensions(), pixGetWpl(), PROCNAME, rotateAMColorCornerLow(), and VERY_SMALL_ANGLE.
Referenced by pixRotateAMCorner().
PIX* pixRotateAMGrayCorner (PIX * pixs, l_float32 angle, l_uint8 grayval)
pixRotateAMGrayCorner()
Input: pixs angle (radians; clockwise is positive) grayval (0 to bring in BLACK, 255 for WHITE) Return: pixd, or null on error
Notes: (1) Rotates the image about the UL corner. (2) A positive angle gives a clockwise rotation. (3) Specify the grayvalue to be brought in from outside the image.
Definition at line 368 of file rotateam.c.
References ERROR_PTR, L_ABS, NULL, pixClone(), pixCreateTemplate(), pixGetData(), pixGetDepth(), pixGetDimensions(), pixGetWpl(), PROCNAME, rotateAMGrayCornerLow(), and VERY_SMALL_ANGLE.
Referenced by pixRotateAMCorner().
PIX* pixRotateAMColorFast (PIX * pixs, l_float32 angle, l_uint32 colorval)
pixRotateAMColorFast()
Input: pixs angle (radians; clockwise is positive) colorval (e.g., 0 to bring in BLACK, 0xffffff00 for WHITE) Return: pixd, or null on error
Notes: (1) This rotates a color image about the image center. (2) A positive angle gives a clockwise rotation. (3) It uses area mapping, dividing each pixel into 16 subpixels. (4) It is about 10% to 20% faster than the more accurate linear interpolation function pixRotateAMColor(), which uses 256 subpixels.
*** Warning: implicit assumption about RGB component ordering ***
Definition at line 422 of file rotateam.c.
References ERROR_PTR, L_ABS, NULL, pixClone(), pixCreateTemplate(), pixGetData(), pixGetDepth(), pixGetDimensions(), pixGetWpl(), PROCNAME, rotateAMColorFastLow(), and VERY_SMALL_ANGLE.
Referenced by main(), and RotateTest().
Variable Documentation
const l_float32 VERY_SMALL_ANGLE = 0.001 [static]
Definition at line 90 of file rotateam.c.
Referenced by pixRotateAM(), pixRotateAMColor(), pixRotateAMColorCorner(), pixRotateAMColorFast(), pixRotateAMCorner(), pixRotateAMGray(), and pixRotateAMGrayCorner().