Leptonica: prog/scale_reg.c File Reference
scale_reg.c File Reference
This tests a number of scaling operations, through the pixScale() interface.
#include "allheaders.h"
Functions
static void AddScaledImages (PIXA *pixa, const char *fname, l_int32 width)
static void PixSave32 (PIXA *pixa, PIX *pixc)
static void PixaSaveDisplay (PIXA *pixa, L_REGPARAMS *rp)
main (int argc, char **argv)
Variables
static const char * image [10]
static const l_int32 SPACE = 30
static const l_int32 WIDTH = 300
static const l_float32 FACTOR [5] = {2.3, 1.5, 1.1, 0.6, 0.3}
Detailed Description
This tests a number of scaling operations, through the pixScale() interface.
Definition in file scale_reg.c.
Function Documentation
static void AddScaledImages (PIXA * pixa, const char * fname, l_int32 width) [static]
Definition at line 236 of file scale_reg.c.
References FACTOR, pixConvertTo32(), pixDestroy(), pixGetWidth(), pixRead(), pixSaveTiled(), pixScale(), and SPACE.
Referenced by main().
static void PixSave32 (PIXA * pixa, PIX * pixc) [static]
Definition at line 264 of file scale_reg.c.
References pixConvertTo32(), pixDestroy(), pixSaveTiled(), and SPACE.
Referenced by main().
static void PixaSaveDisplay (PIXA * pixa, L_REGPARAMS * rp) [static]
Definition at line 275 of file scale_reg.c.
References L_RegParams::display, IFF_JFIF_JPEG, NULL, pixaDestroy(), pixaDisplay(), pixDestroy(), pixDisplayWithTitle(), and regTestWritePixAndCheck().
Referenced by main().
main (int argc, char ** argv)
Definition at line 46 of file scale_reg.c.
References AddScaledImages(), IFF_JFIF_JPEG, IFF_PNG, image, pixaCreate(), PixaSaveDisplay(), pixDestroy(), pixRead(), PixSave32(), pixSaveTiled(), pixScale(), pixScaleToGray16(), pixScaleToGray3(), pixScaleToGray4(), pixScaleToGray6(), pixScaleToGray8(), regTestCleanup(), regTestSetup(), regTestWritePixAndCheck(), SPACE, and WIDTH.
Variable Documentation
const char* image[10] [static]
Initial value:
 {"feyn.tif",
                                "weasel2.png",
                                "weasel2.4c.png",
                                "weasel4.png",
                                "weasel4.16c.png",
                                "weasel8.png",
                                "weasel8.240c.png",
                                "test16.png",
                                "marge.jpg",
                                "test24.jpg"}
Definition at line 25 of file scale_reg.c.
Referenced by main().
const l_int32 SPACE = 30 [static]
Definition at line 37 of file scale_reg.c.
Referenced by AddScaledImages(), main(), and PixSave32().
const l_int32 WIDTH = 300 [static]
Definition at line 38 of file scale_reg.c.
Referenced by main().
const l_float32 FACTOR[5] = {2.3, 1.5, 1.1, 0.6, 0.3} [static]
Definition at line 39 of file scale_reg.c.
Referenced by AddScaledImages().