Leptonica: prog/skew_reg.c File Reference
skew_reg.c File Reference
Regression test for skew detection.
#include "allheaders.h"
Defines
#define DESKEW_REDUCTION 4
#define SWEEP_RANGE 5.
#define SWEEP_DELTA 0.2
#define SWEEP_REDUCTION 2
#define SWEEP_RANGE2 5.
#define SWEEP_DELTA2 1.
#define SWEEP_REDUCTION2 2
#define SEARCH_REDUCTION 2
#define SEARCH_MIN_DELTA 0.01
Functions
main (int argc, char **argv)
Variables
static const l_int32 BORDER = 150
Detailed Description
Regression test for skew detection.
Definition in file skew_reg.c.
Define Documentation
#define DESKEW_REDUCTION 4
Definition at line 25 of file skew_reg.c.
#define SWEEP_RANGE 5.
Definition at line 28 of file skew_reg.c.
#define SWEEP_DELTA 0.2
Definition at line 29 of file skew_reg.c.
#define SWEEP_REDUCTION 2
Definition at line 30 of file skew_reg.c.
#define SWEEP_RANGE2 5.
Definition at line 33 of file skew_reg.c.
#define SWEEP_DELTA2 1.
Definition at line 34 of file skew_reg.c.
#define SWEEP_REDUCTION2 2
Definition at line 35 of file skew_reg.c.
#define SEARCH_REDUCTION 2
Definition at line 36 of file skew_reg.c.
#define SEARCH_MIN_DELTA 0.01
Definition at line 37 of file skew_reg.c.
Function Documentation
main (int argc, char ** argv)
Definition at line 42 of file skew_reg.c.
References BORDER, L_RegParams::display, IFF_PNG, L_BRING_IN_WHITE, L_ROTATE_SAMPLING, L_SHEAR_ABOUT_CENTER, NULL, PIX_CLR, PIX_SRC, pixaCreate(), pixAddBorder(), pixaDestroy(), pixaDisplay(), pixCreate(), pixDestroy(), pixDisplayWithTitle(), pixFindSkewOrthogonalRange(), pixFindSkewSweepAndSearchScorePivot(), pixGetDimensions(), pixRasterop(), pixRead(), pixReduceRankBinaryCascade(), pixRemoveBorder(), pixRotate(), pixRotateBySampling(), pixSaveTiled(), pixSetOrClearBorder(), regTestCleanup(), regTestSetup(), regTestWritePixAndCheck(), startTimer(), and stopTimer().
Variable Documentation
const l_int32 BORDER = 150 [static]
Definition at line 39 of file skew_reg.c.
Referenced by main().