Leptonica: prog/subpixel_reg.c File Reference
subpixel_reg.c File Reference
Regression test for subpixel scaling.
#include "allheaders.h"
Functions
void AddTextAndSave (PIXA *pixa, PIX *pixs, l_int32 newrow, L_BMF *bmf, const char *textstr, l_int32 location, l_uint32 val)
main (int argc, char **argv)
Variables
const char * textstr []
Detailed Description
Regression test for subpixel scaling.
Definition in file subpixel_reg.c.
Function Documentation
void AddTextAndSave (PIXA * pixa, PIX * pixs, l_int32 newrow, L_BMF * bmf, const char * textstr, l_int32 location, l_uint32 val)
Definition at line 175 of file subpixel_reg.c.
References pixAddSingleTextblock(), pixaGetCount(), pixDestroy(), and pixSaveTiledOutline().
Referenced by main().
main (int argc, char ** argv)
Definition at line 35 of file subpixel_reg.c.
References AddTextAndSave(), bmfCreate(), bmfDestroy(), L_RegParams::display, FALSE, IFF_JFIF_JPEG, IFF_PNG, kernelDestroy(), L_ADD_ABOVE, L_ADD_BELOW, L_SUBPIXEL_ORDER_BGR, L_SUBPIXEL_ORDER_RGB, L_SUBPIXEL_ORDER_VBGR, L_SUBPIXEL_ORDER_VRGB, makeGaussianKernel(), makeGaussianKernelSep(), NULL, pixaCreate(), pixAddSingleTextblock(), pixaDestroy(), pixaDisplay(), pixConvertGrayToSubpixelRGB(), pixConvertTo32(), pixConvertTo8(), pixConvertToSubpixelRGB(), pixConvolve(), pixConvolveSep(), pixDestroy(), pixDisplayWithTitle(), pixRead(), pixScale(), regTestCleanup(), regTestComparePix(), regTestSetup(), regTestWritePixAndCheck(), startTimer(), stopTimer(), and textstr.
Variable Documentation
const char* textstr[]
Initial value:
           {"Downscaled with sharpening",
            "Subpixel scaling; horiz R-G-B",
            "Subpixel scaling; horiz B-G-R",
            "Subpixel scaling; vert R-G-B",
            "Subpixel scaling; vert B-G-R"}
Definition at line 28 of file subpixel_reg.c.
Referenced by main(), and pixDisplayColorArray().