Leptonica: prog/xformbox_reg.c File Reference
xformbox_reg.c File Reference
Tests ordered box transforms (rotation, scaling, translation). Also tests the various box hashing graphics operations.
#include "allheaders.h"
Functions
l_int32 RenderTransformedBoxa (PIX *pixt, BOXA *boxa, l_int32 i)
main (int argc, char **argv)
Variables
static const l_int32 SHIFTX_2 = 50
static const l_int32 SHIFTY_2 = 70
static const l_float32 SCALEX_2 = 1.17
static const l_float32 SCALEY_2 = 1.13
static const l_float32 ROTATION_2 = 0.10
static const l_int32 SHIFTX_3 = 44
static const l_int32 SHIFTY_3 = 39
static const l_float32 SCALEX_3 = 0.83
static const l_float32 SCALEY_3 = 0.78
static const l_float32 ROTATION_3 = 0.11
Detailed Description
Tests ordered box transforms (rotation, scaling, translation). Also tests the various box hashing graphics operations.
Definition in file xformbox_reg.c.
Function Documentation
l_int32 RenderTransformedBoxa (PIX * pixt, BOXA * boxa, l_int32 i)
Definition at line 269 of file xformbox_reg.c.
References boxaGetBox(), boxaGetCount(), boxDestroy(), L_CLONE, and pixRenderHashBoxArb().
Referenced by main().
main (int argc, char ** argv)
Definition at line 43 of file xformbox_reg.c.
References boxaAffineTransform(), boxaDestroy(), boxaGetBox(), boxaGetCount(), boxaRotate(), boxaScale(), boxaTransformOrdered(), boxaTranslate(), boxCreate(), boxDestroy(), createMatrix2dRotate(), createMatrix2dScale(), createMatrix2dTranslate(), IFF_PNG, L_BRING_IN_WHITE, L_CLONE, l_productMat3(), L_RO_SC_TR, L_RO_TR_SC, L_SC_RO_TR, L_SC_TR_RO, L_SET_PIXELS, L_TR_RO_SC, L_TR_SC_RO, lept_free(), NULL, pixaCreate(), pixAddBorderGeneral(), pixaDestroy(), pixaDisplay(), pixClipRectangle(), pixCloseBrick(), pixConnComp(), pixConvertTo32(), pixConvertTo8(), pixCopy(), pixDestroy(), pixDisplay(), pixGetDimensions(), pixOpenBrick(), pixRead(), pixRenderHashBox(), pixRenderHashBoxArb(), pixRenderHashBoxBlend(), pixRotateAM(), pixSaveTiled(), pixScale(), pixTranslate(), pixWrite(), RenderTransformedBoxa(), ROTATION_2, ROTATION_3, SCALEX_2, SCALEX_3, SCALEY_2, SCALEY_3, SHIFTX_2, SHIFTX_3, SHIFTY_2, and SHIFTY_3.
Variable Documentation
const l_int32 SHIFTX_2 = 50 [static]
Definition at line 26 of file xformbox_reg.c.
Referenced by main().
const l_int32 SHIFTY_2 = 70 [static]
Definition at line 27 of file xformbox_reg.c.
Referenced by main().
const l_float32 SCALEX_2 = 1.17 [static]
Definition at line 28 of file xformbox_reg.c.
Referenced by main().
const l_float32 SCALEY_2 = 1.13 [static]
Definition at line 29 of file xformbox_reg.c.
Referenced by main().
const l_float32 ROTATION_2 = 0.10 [static]
Definition at line 30 of file xformbox_reg.c.
Referenced by main().
const l_int32 SHIFTX_3 = 44 [static]
Definition at line 33 of file xformbox_reg.c.
Referenced by main().
const l_int32 SHIFTY_3 = 39 [static]
Definition at line 34 of file xformbox_reg.c.
Referenced by main().
const l_float32 SCALEX_3 = 0.83 [static]
Definition at line 35 of file xformbox_reg.c.
Referenced by main().
const l_float32 SCALEY_3 = 0.78 [static]
Definition at line 36 of file xformbox_reg.c.
Referenced by main().
const l_float32 ROTATION_3 = 0.11 [static]
Definition at line 37 of file xformbox_reg.c.
Referenced by main().